In [1]:
import numpy as np
import pandas as pd

- 导入文件 kol数据 粉丝数目大于10w

In [2]:
df_kol = pd.read_csv('D:/datasets/qianyi/user_label/file/kollist_gt10w.csv',encoding='utf-8')
df_kol

D:\software\anaconda\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py:3437: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label
0,5818685711,Rose宫正,0,f,海外,英国,7,·呼市二中12级,NaN,2000-03-01,104026.0,2001.0,5917.0,否极泰来 进一寸有一寸的欢喜,NaN,NaN
1,5264989659,锦鲤宝宝呀,0,f,上海,NaN,7,NaN,NaN,1997-02-13,102032.0,155.0,1.0,锦鲤宝宝工作室主理人,NaN,NaN
2,5456865382,摩登兄弟刘宇宁,0,m,辽宁,NaN,7,NaN,NaN,1990-01-08,13379815.0,118.0,1056.0,工作邮箱：mdlynmd@126.com,歌手、演员 超话粉丝大咖（摩登兄弟超话）,NaN
3,1878021713,根松仁波且,0,m,西藏,昌都,0,NaN,NaN,NaN,102226.0,804.0,2572.0,http://www.warabuddhism.com/ 瓦拉五明佛学院； 微信公众平台：w...,西藏瓦拉五明佛学院院长,"佛法,菩提,佛教"
4,2606919782,水瓶座-心理学,0,f,江苏,南京,7,·南京大学07级,·中国工商银行股份有限公司·中国石油化工股份有限公司·中国联合网络通信股份有限公司,1989-02-16,5826613.0,194.0,16565.0,解析水瓶座的心理学！~~~~~~~~~ 喜欢就 【✚加关注】｡◕‿◕｡ | 合作QQ：148...,知名情感博主,"星座命理,Aquarius,水瓶女"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200287,6150978462,夜店弹脑门,1,m,NaN,NaN,6,NaN,NaN,NaN,134002.0,346.0,2650.0,卡我你家割割抠脚10年,婚姻家庭咨询师二级 张妙幸,NaN
200288,2609421507,天津乐天百货文化中心店,1,m,NaN,NaN,0,NaN,NaN,NaN,349396.0,616.0,0.0,NaN,天津乐天百货文化中心店官方微博,NaN
200289,3877991588,马来西亚千遇旅拍-婚纱摄影-子照,1,f,NaN,NaN,6,NaN,NaN,NaN,105127.0,291.0,988.0,微信号：elove96，全国热线：400-112-5520官方网站：网站一：http://w...,婚礼博主,NaN
200290,6986398702,饭圈安利少年,1,m,NaN,NaN,4,NaN,NaN,NaN,689126.0,92.0,3065.0,NaN,娱乐博主,NaN
200291,6987662402,剧事,2,f,NaN,NaN,4,NaN,NaN,NaN,103798.0,93.0,301.0,随拍分享，分享你的心情❤,NaN,NaN

- 导入文件 fan-follow数据

In [3]:
df_ff = pd.read_csv('D:/datasets/qianyi/user_label/method/based_on_user_focusing_kol/file/300wfan_follow.csv',encoding='utf-8')
df_ff = df_ff[:200000]
df_ff

                          _id      fan_id  followed_id
0       5138022423_7640214702  5138022423   7640214702
1       5138022423_6989405838  5138022423   6989405838
2       5138022423_6550815288  5138022423   6550815288
3       5138022423_6574713134  5138022423   6574713134
4       5138022423_6688666511  5138022423   6688666511
...                       ...         ...          ...
199995  2657096975_5319635720  2657096975   5319635720
199996  2657096975_5209379474  2657096975   5209379474
199997  2657096975_1804887727  2657096975   1804887727
199998  2657096975_6593871464  2657096975   6593871464
199999  2657096975_6503292740  2657096975   6503292740

[200000 rows x 3 columns]

In [14]:
# len(df_ff['fan_id'].unique())

1997

In [4]:
df_con = pd.merge(df_ff,df_kol,left_on='followed_id',right_on='kol_id',how='inner')    #将fan-follow表格数据与kol表格数据merge
df_con

,_id,fan_id,followed_id,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label
0,5138022423_6989405838,5138022423,6989405838,6989405838,威神V_黄旭熙_LUCAS,1,m,其他,NaN,6,NaN,NaN,1999-01-25,4871232.0,31.0,236.0,威神V(WayV)成员,威神V(WayV)成员 Label V旗下艺人,NaN
1,6046089267_6989405838,6046089267,6989405838,6989405838,威神V_黄旭熙_LUCAS,1,m,其他,NaN,6,NaN,NaN,1999-01-25,4871232.0,31.0,236.0,威神V(WayV)成员,威神V(WayV)成员 Label V旗下艺人,NaN
2,7203717520_6989405838,7203717520,6989405838,6989405838,威神V_黄旭熙_LUCAS,1,m,其他,NaN,6,NaN,NaN,1999-01-25,4871232.0,31.0,236.0,威神V(WayV)成员,威神V(WayV)成员 Label V旗下艺人,NaN
3,5797578181_6989405838,5797578181,6989405838,6989405838,威神V_黄旭熙_LUCAS,1,m,其他,NaN,6,NaN,NaN,1999-01-25,4871232.0,31.0,236.0,威神V(WayV)成员,威神V(WayV)成员 Label V旗下艺人,NaN
4,2925529160_6989405838,2925529160,6989405838,6989405838,威神V_黄旭熙_LUCAS,1,m,其他,NaN,6,NaN,NaN,1999-01-25,4871232.0,31.0,236.0,威神V(WayV)成员,威神V(WayV)成员 Label V旗下艺人,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151144,2232423695_1852941991,2232423695,1852941991,1852941991,汽车大学问,1,m,广东,广州,6,NaN,NaN,NaN,1162699.0,169.0,6514.0,最新鲜的汽车资讯； 最快速的新车报道； 最全面的车型数据；世界顶级名车推荐~掌握全球汽车信息~,汽车博主,"汽車,媒体人,文化"
151145,3186627844_3896524336,3186627844,3896524336,3896524336,Poydpoydpoyd,1,f,海外,泰国,4,NaN,·Unique Model Limited2014年-至今·Universe Interna...,1985-10-05,153926.0,157.0,198.0,大家好，我是Poyd (寶兒)! 工作請聯絡寰宇Unique楊小姐 (Email: adel...,寰宇国际集团旗下艺人/模特,"最美變性人,掃毒,泰國"
151146,6474962178_1905360191,6474962178,1905360191,1905360191,波碧水·BOBIWATER官微,1,f,北京,NaN,4,NaN,NaN,狮子座,179802.0,92.0,15053.0,BOBIWATER官方微博，最新产品发布与介绍,创意娱动科技（北京）有限公司,"3D,水通道,黑脸娃娃"
151147,6474962178_7241672538,6474962178,7241672538,7241672538,娱乐大咖营,2,f,福建,NaN,0,NaN,NaN,1991-07-11,152314.0,171.0,3054.0,NaN,NaN,NaN
151148,6474962178_1239802593,6474962178,1239802593,1239802593,游娱,1,m,江苏,NaN,6,·中国佛学院10级,·,水瓶座,574300.0,1491.0,5319.0,一个不正经的博主！,娱乐博主 微博原创视频博主 人文艺术答主,"杨超越,明星娱乐,明星偶像"

In [5]:
df_con.sort_values('fan_id',inplace=True,ascending=False)    #排序，将同一用户内容集中在一起
df_con

,_id,fan_id,followed_id,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label
81677,7646220516_6534084426,7646220516,6534084426,6534084426,品酒的艺术,1,f,北京,NaN,2,NaN,NaN,NaN,751699.0,351.0,8733.0,我想变成你的酒馆，让你饮尽甘源，而你却如早时的薄雾，消散不见。,美食视频博主,NaN
145647,7646220516_1914186435,7646220516,1914186435,1914186435,真当没想到,1,m,浙江,NaN,7,NaN,NaN,1986-12-17,559622.0,29.0,16705.0,NaN,财经博主,"旅游,美女,穿衣美容"
145648,7646220516_2118999441,7646220516,2118999441,2118999441,一碗黑米范,2,f,广东,深圳,7,·中国海洋大学07级,·International Schools Services,01-01,326839.0,966.0,4801.0,店主一枚 WX：youme_05,NaN,NaN
135571,7646220516_2629141391,7646220516,2629141391,2629141391,绪东谈财经,1,m,广东,NaN,4,NaN,·深圳广发兴投资咨询有限公司,NaN,483514.0,74.0,1249.0,广发兴财经首席专家，专业股市财经解读，最为专业的中国股市市场分析 预判及研读 微博只有这一个...,财经博主 微博原创视频博主,"理财,A股,金融"
99588,7646220516_5147442272,7646220516,5147442272,5147442272,淦麻,1,m,辽宁,沈阳,6,·黑龙江科技大学15级,NaN,水瓶座,477353.0,33.0,504.0,哔叻哔叻：老淦麻,搞笑幽默博主 微博原创视频博主,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26203,1008733090_2145291155,1008733090,2145291155,2145291155,乡村教师代言人-马云,1,m,浙江,NaN,7,NaN,NaN,0001-00-00,26119209.0,1.0,197.0,NaN,马云公益基金会创始人,NaN
106476,1008733090_1734741902,1008733090,1734741902,1734741902,王自如ZEALER,1,m,香港,其他,7,·香港理工大学08级·香港理工大学,·www.ZEALER.com2012年-至今·IPSOS Healthcare2009年-...,1988-06-05,1988857.0,385.0,5540.0,ZEALER -- Technology Stays True Here.,ZEALER创始人&CEO,NaN
85055,1008733090_1197161814,1008733090,1197161814,1197161814,李开复,1,m,北京,东城区,7,NaN,·创新工场2009年-至今·谷歌中国2005年-2009年·微软亚洲研究院1998年-2000年,1961-12-03,51534788.0,628.0,14371.0,创新工场CEO，媒体联系：press@chuangxin.com,创新工场董事长兼首席执行官,"风险投资,微博控,创新工场"
8313,1008733090_1713926427,1008733090,1713926427,1713926427,微博搞笑排行榜,1,f,广东,NaN,7,NaN,NaN,0001-00-00,57343725.0,907.0,21876.0,榜姐每日话题 博主。每晚22:00发互动话题,知名搞笑幽默博主,"搞笑,段子,趣图"
11760,1008733090_1771925961,1008733090,1771925961,1771925961,小米公司,1,m,北京,海淀区,7,NaN,NaN,2010-04-06,13863168.0,973.0,19376.0,让全球每个人都能享受科技带来的美好生活。,小米科技有限责任公司,"小米,雷军,发烧友"

In [6]:
df_con_test = df_con
df_con_test = df_con_test.reset_index(drop=True)                #重新排列索引
df_con_test

,_id,fan_id,followed_id,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label
0,7646220516_6534084426,7646220516,6534084426,6534084426,品酒的艺术,1,f,北京,NaN,2,NaN,NaN,NaN,751699.0,351.0,8733.0,我想变成你的酒馆，让你饮尽甘源，而你却如早时的薄雾，消散不见。,美食视频博主,NaN
1,7646220516_1914186435,7646220516,1914186435,1914186435,真当没想到,1,m,浙江,NaN,7,NaN,NaN,1986-12-17,559622.0,29.0,16705.0,NaN,财经博主,"旅游,美女,穿衣美容"
2,7646220516_2118999441,7646220516,2118999441,2118999441,一碗黑米范,2,f,广东,深圳,7,·中国海洋大学07级,·International Schools Services,01-01,326839.0,966.0,4801.0,店主一枚 WX：youme_05,NaN,NaN
3,7646220516_2629141391,7646220516,2629141391,2629141391,绪东谈财经,1,m,广东,NaN,4,NaN,·深圳广发兴投资咨询有限公司,NaN,483514.0,74.0,1249.0,广发兴财经首席专家，专业股市财经解读，最为专业的中国股市市场分析 预判及研读 微博只有这一个...,财经博主 微博原创视频博主,"理财,A股,金融"
4,7646220516_5147442272,7646220516,5147442272,5147442272,淦麻,1,m,辽宁,沈阳,6,·黑龙江科技大学15级,NaN,水瓶座,477353.0,33.0,504.0,哔叻哔叻：老淦麻,搞笑幽默博主 微博原创视频博主,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151144,1008733090_2145291155,1008733090,2145291155,2145291155,乡村教师代言人-马云,1,m,浙江,NaN,7,NaN,NaN,0001-00-00,26119209.0,1.0,197.0,NaN,马云公益基金会创始人,NaN
151145,1008733090_1734741902,1008733090,1734741902,1734741902,王自如ZEALER,1,m,香港,其他,7,·香港理工大学08级·香港理工大学,·www.ZEALER.com2012年-至今·IPSOS Healthcare2009年-...,1988-06-05,1988857.0,385.0,5540.0,ZEALER -- Technology Stays True Here.,ZEALER创始人&CEO,NaN
151146,1008733090_1197161814,1008733090,1197161814,1197161814,李开复,1,m,北京,东城区,7,NaN,·创新工场2009年-至今·谷歌中国2005年-2009年·微软亚洲研究院1998年-2000年,1961-12-03,51534788.0,628.0,14371.0,创新工场CEO，媒体联系：press@chuangxin.com,创新工场董事长兼首席执行官,"风险投资,微博控,创新工场"
151147,1008733090_1713926427,1008733090,1713926427,1713926427,微博搞笑排行榜,1,f,广东,NaN,7,NaN,NaN,0001-00-00,57343725.0,907.0,21876.0,榜姐每日话题 博主。每晚22:00发互动话题,知名搞笑幽默博主,"搞笑,段子,趣图"
151148,1008733090_1771925961,1008733090,1771925961,1771925961,小米公司,1,m,北京,海淀区,7,NaN,NaN,2010-04-06,13863168.0,973.0,19376.0,让全球每个人都能享受科技带来的美好生活。,小米科技有限责任公司,"小米,雷军,发烧友"

In [7]:
# df_con_test['fan_id'][3]

7646220516

- 函数val_num 计算dataframe一列中每个词出现的次数，返回id及出现次数

In [8]:
from tqdm import tqdm
import time
def val_num(col):
    a = []           
    b = []
    for i in tqdm(range(len(col))):
        c = col[i]
        if c not in a:
            a.append(c)                 #列表a存放一列中的各值（不重复）
            b.append(1)                 #首次出现元素 次数为1
            index = len(b)-1            
        else:
            b[index] += 1               #再次出现的元素，对应次数加1
    return a,b                          #返回fan_id和其对应的次数

In [9]:
s_t = time.time()
col = df_con_test['fan_id']             #fan_id中各个值出现的次数 即其关注kol的数目
print(val_num(col))
print(time.time()-s_t)

100%|███████████████████████████████████████████████████████████████████████| 151149/151149 [00:10<00:00, 14676.41it/s]

([7646220516, 7645172196, 7645172100, 7645172015, 7645169808, 7645169599, 7645169378, 7645169202, 7644122325, 7644120857, 7644120822, 7642027114, 7642024899, 7642024895, 7642024849, 7642024683, 7642024672, 7642024427, 7642023376, 7642022778, 7642022331, 7642022289, 7642022260, 7642022104, 7640978342, 7640975353, 7640975074, 7640974742, 7640974242, 7639927361, 7638879494, 7637829282, 7637828956, 7637828348, 7637828072, 7636782265, 7636782210, 7636782100, 7636782099, 7636781656, 7636781080, 7636780417, 7636779719, 7636779694, 7635732648, 7635732366, 7635732006, 7635731185, 7635730588, 7635730546, 7634687223, 7634686851, 7634686771, 7634685029, 7634682901, 7634682637, 7633637419, 7633633648, 7632588940, 7632588202, 7632587735, 7632587608, 7632587434, 7632587319, 7632587049, 7632586775, 7632586675, 7632586639, 7632586151, 7631540088, 7631538828, 7631538388, 7631537646, 7631537614, 7630491031, 7630490117, 7629443875, 7629441462, 7629441175, 7629441123, 7629439370, 7628395800, 7628395760, 7628395733, 7628395670, 7628395566, 7628395477, 7628395471, 7628395311, 7628395249, 7628395103, 7628395079, 7628395031, 7628394985, 7628394765, 7628394600, 7628394531, 7628394328, 7628394319, 7628394202, 7628394170, 7628394040, 7628393973, 7628393612, 7628393571, 7628393207, 7628393169, 7628393151, 7628393063, 7628393044, 7628392877, 7628392842, 7628392782, 7628392647, 7628392435, 7628392259, 7628392045, 7628392016, 7628391977, 7628391962, 7628391953, 7628391867, 7628391861, 7628391737, 7628391639, 7628391638, 7628391602, 7628391429, 7628391373, 7628391307, 7628391214, 7628391203, 7628390844, 7628390817, 7628390723, 7628390711, 7627346460, 7626298350, 7626297502, 7626296700, 7626296615, 7626293803, 7625245573, 7624200976, 7624200413, 7624197752, 7624196722, 7623148109, 7622101773, 7622100917, 7622099469, 7617909396, 7616858557, 7615809713, 7615808827, 7614762327, 7611617718, 7611616568, 7611614711, 7610567583, 7609520282, 7608467593, 7607422096, 7607421992, 7604278546, 7604278386, 7604278159, 7604278013, 7604277903, 7604277885, 7604277820, 7604277384, 7604277277, 7604277244, 7604277213, 7604277205, 7604276663, 7604276333, 7604276244, 7604276215, 7604276166, 7604275957, 7604275904, 7604275813, 7604275681, 7604275633, 7604275604, 7604275502, 7604275381, 7604275372, 7604275359, 7604275136, 7604275120, 7604275115, 7604275089, 7604274963, 7604274908, 7604274884, 7604274880, 7604274858, 7604274762, 7604274748, 7604274745, 7604274704, 7604274594, 7604274585, 7604274507, 7604274457, 7604274348, 7604274347, 7604274179, 7604274094, 7604273797, 7604273780, 7604273695, 7604273655, 7604273561, 7604273451, 7604273273, 7604273248, 7604273163, 7603229768, 7603228315, 7603226927, 7602178101, 7601132766, 7601132548, 7600082903, 7600082263, 7597986464, 7597983442, 7596935684, 7595887227, 7592743517, 7591691103, 7590645119, 7590644139, 7589595347, 7588546729, 7585400606, 7584355160, 7582254323, 7581204764, 7580157813, 7579110541, 7578062780, 7578062546, 7574915375, 7573867910, 7573866536, 7571768111, 7571767513, 7569674236, 7569673593, 7569672144, 7566527148, 7565480550, 7565479590, 7564430201, 7564429857, 7563383889, 7563381071, 7563378802, 7561283342, 7559186572, 7559185530, 7558139690, 7556039125, 7553946272, 7552896770, 7551848606, 7550800439, 7550799014, 7550798157, 7549750088, 7548703384, 7548698761, 7545555613, 7543460627, 7543459258, 7542407613, 7542407573, 7541360362, 7540313085, 7540312315, 7540310472, 7534020075, 7532973367, 7531925151, 7530878006, 7530877342, 7530874790, 7523537096, 7523533021, 7521440021, 7520391386, 7514099545, 7514096990, 7512002800, 7512002058, 7510951797, 7509901872, 7508856870, 7507808992, 7505712217, 7505711271, 7504658765, 7500468199, 7500467393, 7499420500, 7499419787, 7499419432, 7499417860, 7498370548, 7498370514, 7497321292, 7496271020, 7495224780, 7495223897, 7495222356, 7494175286, 7488934587, 7488931274, 7487883528, 7486837288, 7486837049, 7486834152, 7486833249, 7485784241, 7483689881, 7482639836, 7479494846, 7472157518, 7471108141, 7471106591, 7467962514, 7466914710, 7466913203, 7464812684, 7463768762, 7463764799, 7460620256, 7458525915, 7458525615, 7458523696, 7458523672, 7457475067, 7457474396, 7455378244, 7455377634, 7452234321, 7452229990, 7446991868, 7444893312, 7443845384, 7442793105, 7441744973, 7438603436, 7438602422, 7438598778, 7433356067, 7432310536, 7423918281, 7422871383, 7419726631, 7418678764, 7416583176, 7416580672, 7414482313, 7411335497, 7409238941, 7408194082, 7408194016, 7408193448, 7408192118, 7407142373, 7406097608, 7406097279, 7406096360, 7405045086, 7405044926, 7403999982, 7403998770, 7403998164, 7403996213, 7402949711, 7401899306, 7400853632, 7400851462, 7400850596, 7400850194, 7393513448, 7391417534, 7389317155, 7388271689, 7386171414, 7384076683, 7384074987, 7384073675, 7384072804, 7380930640, 7374637783, 7373590932, 7373587802, 7371492739, 7371490073, 7369395751, 7368345989, 7368345778, 7366249165, 7365726235, 7364152451, 7364151936, 7363104004, 7363102906, 7363102875, 7361005530, 7358911176, 7357860946, 7356811268, 7355765284, 7353668250, 7347373786, 7346323836, 7345277767, 7344228971, 7343180341, 7341084168, 7341083262, 7338985685, 7337939331, 7335842171, 7335841891, 7334791338, 7333744789, 7333742078, 7331647086, 7331646186, 7330596604, 7330595567, 7329550289, 7328500751, 7328500645, 7326401389, 7325356464, 7323256282, 7323255687, 7320113051, 7318015330, 7318012187, 7316966133, 7314868714, 7314868175, 7314866859, 7313822940, 7313819539, 7313817728, 7312770512, 7312769658, 7310676228, 7310672566, 7307529741, 7305434357, 7305432984, 7305431836, 7304385634, 7297045329, 7297040450, 7294945018, 7291800090, 7282361302, 7281313841, 7281313574, 7280264554, 7279215783, 7279215207, 7279215089, 7278171147, 7276072701, 7273975949, 7272924982, 7271879040, 7270826540, 7268730483, 7264536028, 7254053193, 7254052977, 7246713088, 7245660832, 7241468880, 7238322009, 7235175435, 7233082335, 7233082012, 7226787069, 7225737229, 7220496290, 7220496118, 7218400684, 7217348896, 7216302594, 7213155309, 7212111067, 7212110964, 7212110867, 7212110806, 7212110799, 7212110665, 7212110584, 7212110566, 7212110356, 7212110348, 7212110196, 7212110112, 7212109875, 7212109872, 7212109788, 7212109763, 7212109569, 7212109269, 7212109240, 7212109185, 7212108988, 7212108942, 7212108927, 7212108863, 7212108754, 7212108671, 7212108607, 7212108498, 7212108399, 7212108346, 7212108230, 7212107922, 7212107870, 7212107796, 7212107748, 7212107697, 7212107610, 7212107555, 7212107356, 7212107185, 7212107077, 7212106851, 7212106850, 7212106810, 7212106712, 7212106650, 7212106633, 7212106591, 7212106488, 7212106413, 7212106402, 7212106329, 7212106294, 7212106219, 7212106069, 7212105986, 7211057871, 7210012534, 7207914728, 7204770366, 7203721440, 7203719967, 7203717520, 7202671466, 7195333285, 7195329816, 7194283797, 7189040030, 7174361896, 7172262742, 7169116486, 7159680283, 7157580006, 7157579841, 7156532047, 7153390119, 7153386925, 7153385941, 7150245104, 7139757500, 7129268707, 7122978875, 7111444792, 7104103727, 7099909347, 7097814793, 7093619939, 7089427548, 7085230459, 7082084999, 7076839982, 7076839703, 7075793083, 7074747632, 7072650463, 7069503353, 7048531022, 7048530968, 7043286271, 7032800224, 7030706778, 7029656135, 7029655694, 7025464442, 7022313660, 7020217029, 7017073888, 7014973647, 7003442657, 7003440976, 6994002194, 6992957530, 6992957013, 6988763859, 6969888979, 6939480918, 6935286079, 6935286022, 6934234084, 6928994774, 6925845918, 6924798334, 6920604029, 6914315484, 6911168166, 6911165879, 6904874707, 6903826121, 6900683075, 6900681748, 6898584291, 6897534435, 6896487225, 6894389775, 6890196697, 6888096428, 6887051076, 6886000071, 6884955227, 6880760885, 6879707995, 6878662481, 6876563469, 6873415699, 6871319321, 6855594849, 6855591309, 6852448995, 6826230327, 6825181252, 6816797849, 6808404609, 6807359339, 6807357351, 6807355819, 6805258323, 6802113819, 6800018145, 6798972006, 6791631129, 6791630823, 6790581955, 6786387461, 6786386931, 6762271582, 6759124052, 6750737567, 6742348497, 6737105571, 6730810488, 6704596255, 6700405855, 6692014108, 6677336822, 6671043283, 6671041379, 6664751958, 6663700515, 6656362641, 6654264819, 6644830502, 6644830429, 6642734098, 6642732484, 6639585317, 6637491333, 6637487520, 6636440769, 6632245084, 6631196524, 6629099969, 6627005196, 6622810885, 6620710629, 6619661213, 6618615434, 6618615204, 6617566980, 6616516979, 6612320717, 6611276122, 6609174902, 6608128788, 6604981263, 6601835577, 6600786489, 6599742133, 6599739871, 6599738279, 6597645067, 6592400769, 6590304194, 6590303572, 6590302487, 6590300614, 6589254139, 6587158738, 6587156918, 6587155325, 6587154680, 6585059808, 6584013349, 6578770990, 6577719301, 6575625356, 6575623130, 6574575950, 6571429968, 6570381707, 6570378837, 6570378470, 6570378335, 6568282208, 6564088108, 6558844878, 6556749820, 6555701903, 6550455895, 6547311648, 6547310608, 6539969232, 6536827265, 6536825923, 6534730702, 6532630116, 6530531801, 6530531457, 6529485447, 6527386512, 6527385758, 6526338826, 6524244361, 6524240742, 6524240131, 6522145084, 6519002252, 6517949986, 6513757343, 6513757293, 6512706641, 6512705897, 6510612920, 6509563308, 6509561734, 6508513204, 6506417883, 6506417617, 6506417258, 6506414179, 6504321268, 6502223963, 6501175944, 6501174992, 6499079340, 6492785084, 6491736954, 6489637683, 6486496508, 6486495854, 6486495624, 6485445863, 6483349627, 6480204176, 6480199897, 6479154966, 6479152153, 6477058900, 6477055322, 6476009557, 6474962178, 6473913308, 6473909982, 6472863943, 6471811622, 6471811421, 6470762954, 6468670381, 6468669797, 6465523220, 6464472922, 6463426793, 6461327551, 6459229757, 6458183365, 6458181428, 6457135539, 6456085663, 6456083034, 6452937500, 6450842867, 6449794961, 6449794090, 6448746384, 6448746160, 6447698528, 6447694094, 6446649765, 6442454734, 6442452990, 6442451658, 6441406558, 6441405473, 6441405311, 6437211342, 6436160166, 6436159852, 6434067197, 6433019010, 6433017578, 6431969510, 6430921495, 6430918573, 6427774450, 6426727660, 6426722667, 6424630337, 6424627084, 6421482448, 6420432869, 6414143105, 6413095099, 6413093252, 6412047263, 6404704385, 6402608422, 6400510021, 6398413748, 6398411672, 6394220713, 6392120405, 6387930240, 6387929853, 6387929143, 6387925087, 6385831395, 6385828617, 6383735194, 6380587566, 6376394311, 6376392758, 6376390686, 6372201019, 6372200491, 6371152240, 6369054924, 6369053134, 6366958321, 6366953899, 6363808170, 6362760596, 6362759684, 6361714093, 6361712992, 6357517698, 6356470682, 6354371646, 6354370706, 6353324207, 6353322699, 6351230076, 6349128075, 6347033762, 6345985728, 6345983774, 6343885545, 6339695805, 6335498637, 6334451537, 6334451147, 6333402571, 6331305631, 6331303607, 6329209475, 6329206444, 6326061817, 6326061700, 6326059017, 6325012030, 6322918520, 6322914534, 6321869710, 6319772102, 6318723373, 6316623041, 6316622807, 6315578618, 6315577078, 6312429331, 6311380563, 6311379010, 6309284479, 6309283331, 6304041513, 6300893880, 6298798159, 6298797876, 6287264780, 6287263809, 6285168260, 6284120141, 6284118479, 6282019086, 6277828593, 6277828211, 6274683008, 6272583185, 6271534859, 6270487112, 6270484632, 6267341785, 6267339662, 6266294637, 6265246749, 6264197020, 6264195870, 6264194792, 6263144683, 6262099114, 6261051364, 6248464920, 6246369997, 6246369366, 6246367661, 6242174514, 6241128371, 6240079642, 6240077430, 6239027899, 6236934142, 6236932529, 6235883066, 6234835960, 6232736401, 6231691497, 6228545185, 6226445841, 6224352453, 6224347379, 6222252165, 6222250501, 6218056544, 6214910802, 6210720559, 6209671789, 6208618670, 6206523054, 6203376677, 6202331280, 6200233992, 6198137853, 6198137146, 6196037626, 6193942531, 6190796613, 6189744445, 6178210212, 6176117621, 6175068767, 6174017485, 6174017297, 6174016598, 6169825683, 6166675979, 6163532738, 6161436588, 6157238908, 6154097153, 6144660377, 6144656141, 6142560165, 6138368196, 6138366753, 6131028640, 6131025568, 6125785959, 6125783643, 6125782321, 6124733014, 6122637739, 6120542146, 6120540786, 6120539762, 6119490981, 6117393738, 6115299461, 6115296503, 6114247583, 6111103253, 6111102557, 6107957607, 6104814829, 6097469742, 6093278516, 6092227916, 6091179521, 6091178887, 6085938828, 6085936374, 6085935235, 6083842239, 6081742463, 6081742342, 6079645266, 6077547270, 6076498988, 6074402623, 6071259551, 6070207544, 6069160207, 6069159580, 6069159514, 6067061803, 6066016517, 6066015773, 6056579722, 6056578273, 6055526895, 6053430506, 6052383483, 6046091798, 6046089267, 6042944349, 6039799688, 6037705673, 6036656909, 6036654488, 6035607368, 6033510197, 6032461856, 6030365239, 6029314979, 6029314157, 6029313607, 6029313326, 6028267416, 6028263512, 6024073983, 6019879576, 6018826583, 6017780096, 6012538477, 6006247838, 6002053152, 5997859786, 5997858891, 5995760926, 5995760246, 5994709070, 5993663875, 5992616452, 5992612340, 5991567497, 5988419288, 5986322238, 5984227224, 5982127416, 5980034161, 5980031628, 5980030384, 5980030242, 5976884928, 5976883513, 5974789180, 5972692668, 5972689643, 5971644741, 5971643562, 5971642294, 5970594967, 5970593492, 5970592373, 5969548025, 5969546948, 5969546367, 5969545509, 5969544211, 5969543775, 5961158140, 5961157732, 5961157343, 5958012237, 5954867064, 5954866406, 5953814760, 5951717676, 5949625111, 5949622094, 5948572200, 5947526615, 5947525526, 5940185433, 5940184342, 5939134550, 5938087995, 5938087938, 5937041235, 5933895293, 5932846437, 5932843301, 5927600385, 5925504362, 5915021784, 5911874525, 5910827046, 5898240773, 5896146920, 5894050662, 5894047089, 5893001004, 5891950496, 5888807807, 5888806814, 5888806535, 5888804628, 5887757608, 5887754455, 5887754401, 5885658423, 5883561859, 5879367454, 5874125789, 5873076491, 5873074920, 5872030934, 5867835091, 5866788048, 5866787968, 5865738161, 5865737342, 5863641295, 5861543314, 5861540841, 5860495523, 5857349467, 5856298170, 5854205015, 5854199979, 5852103813, 5851058886, 5851056653, 5848961936, 5848957433, 5847912828, 5847909489, 5846862798, 5845816433, 5842670010, 5842668219, 5842667149, 5840571369, 5840571192, 5839524538, 5837425401, 5836374534, 5834282011, 5834278642, 5833231334, 5832183718, 5832182518, 5832180305, 5831133959, 5827986408, 5826937883, 5825893273, 5824844113, 5824840124, 5822745162, 5818551688, 5818548240, 5817503163, 5815406834, 5812262006, 5810164770, 5810162718, 5810160406, 5804921027, 5797580855, 5797578181, 5797577836, 5795481207, 5792335898, 5784995661, 5778703984, 5777657733, 5774510889, 5774510754, 5770318606, 5769269460, 5768220995, 5768220940, 5758783419, 5756686270, 5756682481, 5754586756, 5754585870, 5748293791, 5747250002, 5746199970, 5744100612, 5738858738, 5738858357, 5733616430, 5732569641, 5729423135, 5729420103, 5728371643, 5728371502, 5727326082, 5724176988, 5721035541, 5721031690, 5719987169, 5717889963, 5714742855, 5714740890, 5714739763, 5713694208, 5713693173, 5711596394, 5707399667, 5706351492, 5702159320, 5701111678, 5692719806, 5692719548, 5690626856, 5688526469, 5683286636, 5683285537, 5682236430, 5680139067, 5676993891, 5675945051, 5675944964, 5675944464, 5674897392, 5674896959, 5674894611, 5674894050, 5673849101, 5671752404, 5671749879, 5669654784, 5667558635, 5667558216, 5667556308, 5666505594, 5664412627, 5664412340, 5664410440, 5663364326, 5663360627, 5663360519, 5661263589, 5660218032, 5659166871, 5658121111, 5658117986, 5658117743, 5658117260, 5658116530, 5657070185, 5657068436, 5656022758, 5656021626, 5653926807, 5653926743, 5653923651, 5652874874, 5652873820, 5652873504, 5651828987, 5650780703, 5650777794, 5648683885, 5648682214, 5647632364, 5647631078, 5646586481, 5646584097, 5646581984, 5645538022, 5645537695, 5645537365, 5645534996, 5642391131, 5638198131, 5638197818, 5637148943, 5636097473, 5635049624, 5632955414, 5632952537, 5632951476, 5632950445, 5629806017, 5628760551, 5628756560, 5628756545, 5627711787, 5627711160, 5625610669, 5623518229, 5622468666, 5618272410, 5613030382, 5613029546, 5611979338, 5609881782, 5606738196, 5603594659, 5603593370, 5601496383, 5601493566, 5600446695, 5600444867, 5598348323, 5596253758, 5593107511, 5591011722, 5589959875, 5589959730, 5585765537, 5584717020, 5581570970, 5579477772, 5579477398, 5579474493, 5579473603, 5575283343, 5575281945, 5575280697, 5574232906, 5565846769, 5554308702, 5548019883, 5541727999, 5541725553, 5539631152, 5538580281, 5538579847, 5536484932, 5531241664, 5531239280, 5529143948, 5529142272, 5528095839, 5523900395, 5523898448, 5520757602, 5520756459, 5517610589, 5507122551, 5505029311, 5499783647, 5498737223, 5496637586, 5496635584, 5495588015, 5493492918, 5492445904, 5490347014, 5480909318, 5473568092, 5471471882, 5471471505, 5470425986, 5469375785, 5469373217, 5468324221, 5465179441, 5460987882, 5458891328, 5457840507, 5455741380, 5452598241, 5451550868, 5450500681, 5446304360, 5440017641, 5440017608, 5435818162, 5428479062, 5422186502, 5416945667, 5415896373, 5413798855, 5407509003, 5407507161, 5403316210, 5403312951, 5400171718, 5399120418, 5398069540, 5394924309, 5392828865, 5391778241, 5389684751, 5383392119, 5381294573, 5380244962, 5375001458, 5372904897, 5370809821, 5369759455, 5362420848, 5362417762, 5358223848, 5352983131, 5349835872, 5347741001, 5345640774, 5344594714, 5337255658, 5336208117, 5336207850, 5336206779, 5334107245, 5326766612, 5307893866, 5307892121, 5304746434, 5299505779, 5286922720, 5285876949, 5285876082, 5285873699, 5284828200, 5284827754, 5284827646, 5283775163, 5275387803, 5272242868, 5271194676, 5271193630, 5271192471, 5270145981, 5270143835, 5269097477, 5268049238, 5263854136, 5260707643, 5252321071, 5251272186, 5251271226, 5250224781, 5250222950, 5250220959, 5249176830, 5249176076, 5249173489, 5247078421, 5247077675, 5247076073, 5244981846, 5244980583, 5244979797, 5243930053, 5243929701, 5239738044, 5238686271, 5237639112, 5233446625, 5233445025, 5232394439, 5229252944, 5228203714, 5227155200, 5225058344, 5217719473, 5216670127, 5216665900, 5212471711, 5210378563, 5210377184, 5208282407, 5208281002, 5206183899, 5206181359, 5205135024, 5205134941, 5201989332, 5201988585, 5198843556, 5197793644, 5197793214, 5193599721, 5186260130, 5185210739, 5179968300, 5172629522, 5170533386, 5170531633, 5170531018, 5170529428, 5164241149, 5163188471, 5152703125, 5151656065, 5151655789, 5150607548, 5150606136, 5138022423, 5136977651, 5132782433, 5129637949, 5128586383, 5127541302, 5124396195, 5121247872, 5107614763, 5096079693, 5082453112, 5082451866, 5081401488, 5077210273, 5075109941, 5074064487, 5071964119, 5053090142, 5050992294, 5049944305, 5047849079, 5045750386, 5045748838, 5042604297, 5035267150, 5035264454, 5033167093, 5031067758, 5028974024, 5025826695, 5023728191, 5020586705, 5019536772, 5018488122, 5015342949, 5015340350, 5013245204, 3996127977, 3996125865, 3994028037, 3992982524, 3992979457, 3991932651, 3991931590, 3991929413, 3989835590, 3972007841, 3964667456, 3963622624, 3958377014, 3955232028, 3952084839, 3949989622, 3926917726, 3923775503, 3920628978, 3919581437, 3912240266, 3909095811, 3896513652, 3896512202, 3887072746, 3882880687, 3862958343, 3862958192, 3862957362, 3862954252, 3862954213, 3860858986, 3843035609, 3843031220, 3840938852, 3836744110, 3833597455, 3830451205, 3818915327, 3802140496, 3784314995, 3779069470, 3749712764, 3748659643, 3746562813, 3741319363, 3720349827, 3713012290, 3711964280, 3686796512, 3673162833, 3659533371, 3652195331, 3641706667, 3639609973, 3631221883, 3625977734, 3625975950, 3608153452, 3608152194, 3608150120, 3602910071, 3588229930, 3568306760, 3562014130, 3549432361, 3547333734, 3544190264, 3536848311, 3533702952, 3520069934, 3517977361, 3516925327, 3508537641, 3506443320, 3506440315, 3502246103, 3487566195, 3456108332, 3404726320, 3386904404, 3382710724, 3368031092, 3349152972, 3339719780, 3322939110, 3319796963, 3319795330, 3311403461, 3309309371, 3308260391, 3300920943, 3300918457, 3289382982, 3285189135, 3275754207, 3264221570, 3255833867, 3251634692, 3232762284, 3218081713, 3217034264, 3211789357, 3210740461, 3209696452, 320969

In [10]:
list_user,list_num = val_num(col)
df_user_test = pd.DataFrame(data=list_user,columns=['user_id'])         #转换为dataframe
df_user_test

100%|███████████████████████████████████████████████████████████████████████| 151149/151149 [00:10<00:00, 14046.41it/s]

         user_id
0     7646220516
1     7645172196
2     7645172100
3     7645172015
4     7645169808
...          ...
1989  1084229683
1990  1025509673
1991  1022362744
1992  1011876243
1993  1008733090

[1994 rows x 1 columns]

In [11]:
df_user_test['focus_kol_num'] = pd.Series(list_num)         #添加列 关注kol数目
df_user_test

         user_id  focus_kol_num
0     7646220516             33
1     7645172196            135
2     7645172100             76
3     7645172015             41
4     7645169808             16
...          ...            ...
1989  1084229683             51
1990  1025509673             75
1991  1022362744             50
1992  1011876243             24
1993  1008733090             28

[1994 rows x 2 columns]

## 美妆博主数目

- 导入文件 美妆博主数据

In [15]:
df_makeup_kol = pd.read_csv('D:/datasets/qianyi/user_label/method/based_on_user_focusing_kol/file/makeup_kol_gt10w.csv',encoding='utf-8')
df_makeup_kol

,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con
0,6111217365,你柚有点甜儿,1,f,上海,NaN,7,NaN,NaN,1995-08-31,2012320.0,162.0,1174.0,美妆 时尚 穿搭！,知名美妆博主 微博原创视频博主 微博VLOG博主,"吃喝玩乐,旅游摄影,化妆品","你柚有点甜儿美妆 时尚 穿搭！吃喝玩乐,旅游摄影,化妆品知名美妆博主 微博原创视频博主 微博..."
1,7294063713,六六酱llj,1,f,上海,NaN,4,NaN,NaN,1995-01-01,597497.0,45.0,159.0,专研美妆的资深空乘，有任何美妆方面的问题都可以帮你解决～合作VX:xuyan388（备注来意...,美妆博主 微博原创视频博主,NaN,六六酱llj专研美妆的资深空乘，有任何美妆方面的问题都可以帮你解决～合作VX:xuyan38...
2,7457579680,美妆挖掘机_,1,f,上海,NaN,4,NaN,NaN,1996-05-19,1143680.0,76.0,196.0,只有你想不到的美妆没有我挖不倒 合作加🛰caijia85,美妆博主,"美妆护肤,美妆控","美妆挖掘机_只有你想不到的美妆没有我挖不倒 合作加🛰caijia85美妆护肤,美妆控美妆博主"
3,6358577421,仙女也爱买,1,f,江苏,南京,2,·北京邮电大学09级,·徐州微达文化传播有限公司2016年-2017年,1993-11-28,141203.0,95.0,128824.0,专注种草拔草的美妆博~,时尚博主,"时尚,护肤,美妆","仙女也爱买专注种草拔草的美妆博~时尚,护肤,美妆时尚博主"
4,1564595531,-元气六六,1,f,广东,NaN,7,NaN,·么么哒1998年-2015年,01-01,391819.0,57.0,30109.0,喜欢买喜欢分享的美妆博主。,美妆博主,"口红,化妆,护肤","-元气六六喜欢买喜欢分享的美妆博主。口红,化妆,护肤美妆博主"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9154,2402865684,Angel芭比成都权威整形修复,2,f,NaN,NaN,6,NaN,NaN,NaN,101018.0,189.0,554.0,成都整形美容协会，中国整形协会认证指定修复基地。,NaN,NaN,Angel芭比成都权威整形修复成都整形美容协会，中国整形协会认证指定修复基地。nannan
9155,3964927653,卡通保温杯,1,f,NaN,NaN,0,NaN,NaN,NaN,150807.0,1518.0,2504.0,B365水果酵素养生、美容！想要了解更多的加我微信吧😄yyz20121015,富阳雅高机械维修经营部 会计 李珊,NaN,卡通保温杯B365水果酵素养生、美容！想要了解更多的加我微信吧😄yyz20121015nan...
9156,3911142496,皮肤管理院线美容仪器批发货源,2,f,NaN,NaN,4,NaN,NaN,NaN,114725.0,1723.0,1810.0,皮肤管理美容仪器厂家一手货源💕184 1266 003,NaN,NaN,皮肤管理院线美容仪器批发货源皮肤管理美容仪器厂家一手货源💕184 1266 003nannan
9157,1631766365,丁子Queena,1,f,NaN,NaN,5,NaN,NaN,NaN,198688.0,222.0,458.0,科颜美皮肤管理中心创始人 时尚造型师 知名护肤专家，品牌特邀嘉宾，合作请私信,致美焕颜美容会所创始人,NaN,丁子Queena科颜美皮肤管理中心创始人 时尚造型师 知名护肤专家，品牌特邀嘉宾，合作请私信...
9158,3732781363,西安微整形-Johnny绍伟,1,m,NaN,NaN,6,NaN,NaN,NaN,109155.0,343.0,330.0,wx：1.2号已满 wsw963037950 关注我变美丽,西安唯星颜医疗美容有限公司 主理人,NaN,西安微整形-Johnny绍伟wx：1.2号已满 wsw963037950 关注我变美丽nan...

In [19]:
df_m1 = pd.merge(df_ff,df_makeup_kol,left_on='followed_id',right_on='kol_id',how='inner')   #将fan-follow表格数据与美妆博主表格数据merge
df_m1

,_id,fan_id,followed_id,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con
0,6387925087_5202523130,6387925087,5202523130,5202523130,宝藏橘子耶,2,f,其他,NaN,3,NaN,NaN,1995-01-01,232076.0,122.0,212.0,你与清风明月一样 都是小宝藏,NaN,"美容服饰,视频音乐,钻饰品","宝藏橘子耶你与清风明月一样 都是小宝藏美容服饰,视频音乐,钻饰品nan"
1,5940184342_5202523130,5940184342,5202523130,5202523130,宝藏橘子耶,2,f,其他,NaN,3,NaN,NaN,1995-01-01,232076.0,122.0,212.0,你与清风明月一样 都是小宝藏,NaN,"美容服饰,视频音乐,钻饰品","宝藏橘子耶你与清风明月一样 都是小宝藏美容服饰,视频音乐,钻饰品nan"
2,6046089267_1647256370,6046089267,1647256370,1647256370,少女囤货日记,1,f,海外,NaN,7,NaN,·商务合作私信,NaN,1455995.0,203.0,16645.0,今天你囤货了吗,知名美妆博主 时尚美妆视频自媒体,"时尚,护肤,美妆","少女囤货日记今天你囤货了吗时尚,护肤,美妆知名美妆博主 时尚美妆视频自媒体"
3,6436159852_1647256370,6436159852,1647256370,1647256370,少女囤货日记,1,f,海外,NaN,7,NaN,·商务合作私信,NaN,1455995.0,203.0,16645.0,今天你囤货了吗,知名美妆博主 时尚美妆视频自媒体,"时尚,护肤,美妆","少女囤货日记今天你囤货了吗时尚,护肤,美妆知名美妆博主 时尚美妆视频自媒体"
4,2839544222_1647256370,2839544222,1647256370,1647256370,少女囤货日记,1,f,海外,NaN,7,NaN,·商务合作私信,NaN,1455995.0,203.0,16645.0,今天你囤货了吗,知名美妆博主 时尚美妆视频自媒体,"时尚,护肤,美妆","少女囤货日记今天你囤货了吗时尚,护肤,美妆知名美妆博主 时尚美妆视频自媒体"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249,6315578618_1272282165,6315578618,1272282165,1272282165,姚璇_西子,1,f,浙江,杭州,7,·上海戏剧学院05级·三峡大学01级·沙洋中学98级·姚集中学95级·姚集小学89级,NaN,双子座,643995.0,1734.0,4590.0,汉服模特、coser、演员，商业合作请私信。💕,微博故事红人 时尚美妆视频自媒体,"彩妆,猫咪控,汉服","姚璇_西子汉服模特、coser、演员，商业合作请私信。💕彩妆,猫咪控,汉服微博故事红人 时尚..."
7250,6499079340_5292267592,6499079340,5292267592,5292267592,护肤美妆大佬,1,f,香港,NaN,1,NaN,NaN,NaN,116120.0,374.0,55903.0,遇顺境，处之淡然，遇逆境，处之泰然。,美妆博主,NaN,护肤美妆大佬遇顺境，处之淡然，遇逆境，处之泰然。nan美妆博主
7251,7628395733_1434414634,7628395733,1434414634,1434414634,叔大奥尼,2,m,上海,浦东新区,0,NaN,NaN,天蝎座,152282.0,1912.0,63947.0,话痨，哈哈哈刷屏警告。2只龙猫和1只橘猫的铲屎官。节操是啥？可以吃吗？,NaN,"美容,音樂,旅游美食","叔大奥尼话痨，哈哈哈刷屏警告。2只龙猫和1只橘猫的铲屎官。节操是啥？可以吃吗？美容,音樂,旅..."
7252,2657096975_3698247600,2657096975,3698247600,3698247600,天天教你化妆,1,f,上海,黄浦区,6,NaN,·徐州卓达房地产开发有限公司,1990-05-31,9436521.0,241.0,5993.0,"原来小时候的我们都很性感,都不穿内裤的投稿",美妆博主,"娱乐八卦,服装搭配爱好者,弄潮儿","天天教你化妆原来小时候的我们都很性感,都不穿内裤的投稿娱乐八卦,服装搭配爱好者,弄潮儿美妆博主"
7253,2183140585_2002262597,2183140585,2002262597,2002262597,雪花秀Sulwhasoo,1,f,上海,NaN,6,NaN,·爱茉莉太平洋贸易有限公司,01-01,1164346.0,58.0,8107.0,过去，现在，未来不断精进对美的探寻，以亚洲珍贵草本智慧为灵感来源，致力于打造上乘的美肤方案，...,Sulwhasoo雪花秀化妆品中国官方微博,"打底精华,补水提拉,抗衰老",雪花秀Sulwhasoo过去，现在，未来不断精进对美的探寻，以亚洲珍贵草本智慧为灵感来源，致...

In [21]:
s_t = time.time()
col = df_m1['fan_id']
print(val_num(col))                             #每个用户关注美妆博主的数目
print(time.time()-s_t)

100%|███████████████████████████████████████████████████████████████████████████| 7254/7254 [00:00<00:00, 23072.54it/s]

([6387925087, 5940184342, 6046089267, 6436159852, 2839544222, 5632951476, 1734346281, 2683309400, 6618615434, 5851058886, 7505712217, 5435818162, 5887754455, 5953814760, 5216665900, 5632950445, 5724176988, 5152703125, 5982127416, 5372904897, 2752513311, 3887072746, 5663360519, 5688526469, 5879367454, 6196037626, 7313819539, 7281313841, 6522145084, 6335498637, 5299505779, 6898584291, 2708474711, 5701111678, 6476009557, 7530877342, 5842670010, 6584013349, 5250224781, 2394952295, 5683286636, 7174361896, 6176117621, 2583696274, 2236617681, 5980034161, 6351230076, 5285876949, 3404726320, 6924798334, 5717889963, 5653923651, 6236932529, 1577060963, 6791631129, 2658145312, 6311379010, 6873415699, 6426722667, 5754585870, 6239027899, 3746562813, 5744100612, 5674894611, 3516925327, 2102396423, 2175796887, 5471471505, 5986322238, 5523900395, 5081401488, 6656362641, 6461327551, 5049944305, 5656021626, 6052383483, 1951403167, 2205159330, 5756686270, 6457135539, 5020586705, 7025464442, 7297040450, 6568282208, 5994709070, 2130707327, 2163213213, 6076498988, 5658117260, 7014973647, 2907704435, 2708471847, 6117393738, 2713718575, 5247078421, 7458525915, 5548019883, 2873098245, 2683306062, 5468324221, 5469373217, 2545943802, 7264536028, 7628391977, 3218081713, 2291140720, 7629441462, 5399120418, 6664751958, 7630491031, 1901072083, 2936016687, 2585792442, 7569674236, 7273975949, 7467962514, 7373590932, 5971644741, 6622810885, 2247103173, 5585765537, 2661287101, 6585059808, 3030387813, 6361714093, 7418678764, 5541727999, 5857349467, 5225058344, 5216670127, 3625975950, 6398411672, 6277828211, 7584355160, 5541725553, 3639609973, 5201989332, 3862958192, 5579477772, 5520757602, 7406097608, 6805258323, 6663700515, 1823473980, 5507122551, 3128953532, 1767901820, 6200233992, 2483032267, 5170533386, 2690646624, 5579474493, 1883242757, 2160070602, 7604273163, 7604273655, 7604273695, 7604273780, 7604273797, 7282361302, 7326401389, 7604274347, 7604274457, 7604274704, 7323256282, 7604274748, 7604274858, 7604274963, 7530874790, 3992979457, 7604275381, 7604275502, 7604275681, 7471106591, 7604275904, 7604275957, 7636782265, 7604276663, 5642391131, 7604277244, 5077210273, 7604278546, 7279215089, 5349835872, 7195329816, 5042604297, 7129268707, 5948572200, 6053430506, 5714740890, 7632587434, 7189040030, 7540313085, 6163532738, 5627711160, 6790581955, 5228203714, 6369054924, 5591011722, 3909095811, 5671752404, 5648683885, 7635730546, 6270484632, 6228545185, 7604273273, 7604273561, 7604274585, 7604274908, 7603226927, 7604276166, 7604277277, 7604277820, 7604278013, 6376390686, 5997858891, 6019879576, 3309309371, 5575283343, 3189768370, 5910827046, 5650780703, 5997859786, 1840251830, 5795481207, 2958034731, 2088765381, 6142560165, 6246369366, 5938087938, 1870661961, 2977958254, 7216302594, 2410678723, 1785727537, 5664410440, 5733616430, 5170531633, 3195014850, 5460987882, 5458891328, 5244981846, 7157579841, 2132805171, 6430918573, 7565480550, 5667558635, 7411335497, 5832180305, 5531239280, 2087716404, 6240077430, 5971642294, 6547310608, 7455377634, 7569673593, 2391805985, 1842349087, 6125783643, 1805651092, 7406097279, 5756682481, 3862954252, 6826230327, 5714739763, 5601493566, 6157238908, 5579473603, 6442451658, 6436160166, 5810160406, 1241515251, 7099909347, 7401899306, 6092227916, 6309283331, 7333742078, 6311380563, 6904874707, 7640975074, 5645534996, 1940915945, 5658117986, 6464472922, 1175455614, 7640975353, 1914701893, 7363102875, 5233445025, 7338985685, 3039824127, 1797261550, 6222252165, 5185210739, 6920604029, 2671774151, 6599739871, 6304041513, 7642024683, 5680139067, 1213205403, 2337279007, 6786386931, 5974789180, 7212108927, 1761610864, 7626296615, 7017073888, 6590303572, 6485445863, 6334451147, 5536484932, 5729423135, 6035607368, 7210012534, 6334451537, 7406096360, 7505711271, 7335842171, 5210378563, 6555701903, 2614104831, 6024073983, 7634686851, 5894050662, 7626298350, 6642734098, 5845816433, 7563378802, 6208618670, 7642022104, 7346323836, 6530531801, 7509901872, 6600786489, 5023728191, 7270826540, 7020217029, 6524240742, 7323255687, 2694841300, 6479152153, 5598348323, 5589959730, 1915749445, 7405045086, 7642023376, 2560624342, 7644120857, 2872051450, 2642413341, 7510951797, 6631196524, 3972007841, 7632586675, 7220496290, 7457474396, 7629441123, 2291140935, 7563381071, 6017780096, 7590644139, 5457840507, 7169116486, 7616858557, 7642024427, 5170531018, 7642024672, 2124417800, 7316966133, 7345277767, 7497321292, 7642024899, 3061844741, 7642024895, 6547311648, 7357860946, 5675945051, 7003442657, 6427774450, 1916800575, 2291142255, 3896512202, 7558139690, 6878662481, 6241128371, 6161436588, 2687504397, 7500468199, 7551848606, 7471108141, 7523537096, 7520391386, 7486837049, 6198137146, 6266294637, 6486495624, 6480204176, 6383735194, 5646586481, 6627005196, 7499420500, 2908754875, 6424630337, 7563383889, 3339719780, 7391417534, 7642022260, 6232736401, 6354371646, 1808794634, 6322914534, 5243930053, 6111102557, 7597983442, 7368345778, 6564088108, 7075793083, 6107957607, 7574915375, 7458523672, 6234835960, 5018488122, 7532973367, 7365726235, 5389684751, 1967132721, 3784314995, 6319772102, 6210720559, 2350907602, 5613029546, 7642024849, 6083842239, 7530878006, 1854932363, 2351958277, 5851056653, 7498370548, 6644830429, 3047167045, 5663364326, 5980030242, 5628756545, 6671041379, 7604274179, 7032800224, 7604274594, 7604274762, 7604275115, 5682236430, 5127541302, 7604277903, 7604278159, 2415924044, 3896513652, 7603229768, 3041919821, 5045748838, 6272583185, 6459229757, 6264195870, 5593107511, 6033510197, 1863323773, 6506414179, 7531925151, 1740640480, 7330596604, 7622101773, 6434067197, 7150245104, 7488934587, 6138368196, 2614104683, 5746199970, 6413095099, 2763003071, 5307892121, 2523923167, 6587155325, 1586496603, 5847909489, 6570378470, 3588229930, 5239738044, 6441406558, 3919581437, 5915021784, 7463768762, 5638197818, 5249173489, 5831133959, 5252321071, 7624200413, 6574575950, 7355765284, 5170529428, 5836374534, 5856298170, 7571767513, 6612320717, 5970592373, 1831862814, 5446304360, 5674894050, 5375001458, 5128586383, 5652874874, 6526338826, 6558844878, 3035629497, 3322939110, 2297432151, 1674578333, 5352983131, 1840253470, 5452598241, 7172262742, 3955232028, 5888806535, 6556749820, 6193942531, 1747980831, 6372201019, 6486495854, 1734349565, 6028263512, 6802113819, 5416945667, 3958377014, 7408192118, 6539969232, 6888096428, 6300893880, 2582643692, 6601835577, 7441744973, 5465179441, 3818915327, 5661263589, 5071964119, 7356811268, 7122978875, 5873076491, 3508537641, 5969545509, 5392828865, 6441405473, 5954866406, 5995760926, 5205134941, 6002053152, 2150634264, 5664412340, 5969548025, 5638198131, 6037705673, 7089427548, 7595887227, 5247077675, 5863641295, 6825181252, 3862954213, 2265973147, 3180332004, 1913652445, 6886000071, 5797578181, 1815087072, 7458523696, 6326061700, 6093278516, 5839524538, 7466914710, 5575280697, 5939134550, 1870660163, 6070207544, 6477055322, 3608152194, 3506440315, 7341084168, 5770318606, 6169825683, 7297045329, 5721035541, 6069159514, 2290091540, 2773483781, 5529142272, 7604273451, 7604274094, 7604274745, 7604274884, 7604275359, 7603228315, 7604274348, 7604275120, 7604276244, 7604273248, 7604275372, 7604275604, 7604276333, 6144656141, 7029655694, 6032461856, 6321869710, 5496635584, 1969226473, 3608150120, 5628756560, 2718958351, 2630878293, 6570378335, 6069159580, 2316307877, 6463426793, 7556039125, 1422919762, 6085938828, 5270143835, 5826937883, 1751126254, 7104103727, 2969569491, 7559186572, 3210740461, 7582254323, 7457475067, 7139757500, 6318723373, 7645172196, 6085935235, 6122637739, 2353004795, 6366953899, 6808404609, 6619661213, 5827986408, 2619343925, 5015340350, 5473568092, 6331303607, 6509561734, 6508513204, 3232762284, 3568306760, 5210377184, 6398413748, 5648682214, 6890196697, 5637148943, 2232423695, 3138393303, 6577719301, 3720349827, 6473913308, 5748293791, 2980054561, 3830451205, 5284827646, 6006247838, 6575625356, 7604275633, 7604276215, 7604277213, 1989149391, 6085936374, 7384073675, 2006977311, 7159680283, 5866788048, 7550798157, 7157580006, 7330595567, 6174016598, 5275387803, 7443845384, 6570381707, 3502246103, 5574232906, 7335841891, 1864368784, 5980030384, 1873808150, 1998589292, 5896146920, 6935286022, 7358911176, 7388271689, 7514096990, 7361005530, 5947525526, 6372200491, 1869615411, 6855594849, 5217719473, 7423918281, 6316622807, 5797577836, 3631221883, 6333402571, 7438602422, 5646581984, 7604277205, 7604277885, 6029314979, 5887754401, 3741319363, 7314866859, 5972689643, 6517949986, 5658117743, 3533702952, 6442452990, 7400851462, 7632586775, 6174017485, 2614102482, 5344594714, 5774510889, 5362420848, 5531241664, 6504321268, 3749712764, 6632245084, 6759124052, 5609881782, 7403998164, 7313817728, 7022313660, 2687500891, 5334107245, 3779069470, 6206523054, 6174017297, 1084229683, 7374637783, 2421164870, 5840571192, 6575623130, 3920628978, 7632588202, 5972692668, 5227155200, 5539631152, 5129637949, 7548703384, 2674922390, 2133857160, 6486496508, 1642071512, 5538580281, 5832183718, 2149585017, 3991929413, 5738858357, 6524244361, 3186627844, 2033191457, 6267339662, 3015705561, 5237639112, 1951401805, 1583353113, 7207914728, 1846546614, 6611276122, 5658121111, 6224347379, 7534020075, 6896487225, 6472863943, 5732569641, 5470425986, 3197113400, 5554308702, 7630490117, 2010122961, 5201988585, 2194673857, 5627711787, 2672820597, 6363808170, 3285189135, 3308260391, 5747250002, 6534730702, 5866787968, 2170557313, 1955594463, 2112881787, 6074402623, 6111103253, 2258637334, 7442793105, 5721031690, 7389317155, 7588546729, 5961157343, 5817503163, 7400853632, 5523898448, 2629829335, 2863662047, 7279215783, 5784995661, 3860858986, 7596935684, 1833962342, 6513757343, 7600082263, 3544190264, 7631540088, 7458525615, 5206181359, 6039799688, 5854205015, 6222250501, 6879707995, 2014316040, 1795163750, 2055210655, 1950355587, 2969572061, 7631537646, 6081742342, 7494175286, 5932846437, 7629443875, 6880760885, 5407509003, 5848961936, 6339695805, 5635049624, 6263144683, 5865737342, 5719987169, 3189769312, 2407533263, 7512002058, 5645537695, 6742348497, 5238686271, 6448746160, 7523533021, 6420432869, 5971643562, 5893001004, 2319455050, 5980031628, 1799358551, 2435842357, 6029313326, 5754586756, 7314868714, 2300579663, 5713693173, 2670726003, 6236934142, 6097469742, 7642022331, 7615808827, 5469375785, 7276072701, 6261051364, 3923775503, 6036656909, 5834282011, 7485784241, 7604275813, 1815086872, 7212105986, 7212106069, 7212106219, 7212106402, 7212106413, 7212107077, 7212107185, 7212107356, 7212107555, 7212107610, 7212107748, 7212107796, 7212107922, 7212108498, 7212108607, 7212108754, 7212108863, 7212109185, 7212109269, 7212109875, 7212110112, 7212110196, 7212110356, 7212110348, 7212110964, 7212111067, 5951717676, 6458181428, 7344228971, 6442454734, 2298479943, 6473909982, 5369759455, 6345983774, 5499783647, 7341083262, 2531266027, 7369395751, 1670385374, 5047849079, 6231691497, 5804921027, 6928994774, 6700405855, 7076839703, 3926917726, 5888804628, 6380587566, 6267341785, 7569672144, 3174043831, 5653926743, 5243929701, 5656022758, 6055526895, 2500855794, 6125782321, 2462058965, 2134903467, 6449794961, 2889875755, 6447694094, 7384072804, 6536827265, 7203717520, 7585400606, 7386171414, 6437211342, 5596253758, 6465523220, 3120566062, 3964667456, 7581204764, 7542407613, 7486833249, 5611979338, 7635732006, 6570378837, 5025826695, 5272242868, 6592400769, 5172629522, 6394220713, 6131028640, 3840938852, 3172996364, 7633633648, 7645169378, 7432310536, 6322918520, 5398069540, 6934234084, 3082815103, 6529485447, 2116030091, 3713012290, 1011876243, 3289382982, 5625610669, 2897216585, 2925529160, 5381294573, 2140147024, 3164606267, 5888807807, 7400850194, 6992957013, 2651852633, 3168798325, 7320113051, 3368031092, 1837105693, 7093619939, 3996127977, 3386904404, 7542407573, 5212471711, 2138047350, 1764754532, 1678771360, 6897534435, 5035264454, 3549432361, 2508196815, 6491736954, 5911874525, 5861543314, 1923092867, 5632955414, 3199206421, 5652873820, 5096079693, 5976883513, 5380244962, 6629099969, 2500857735, 5769269460, 5992616452, 6894389775, 3122662885, 7566527148, 5842668219, 7337939331, 6512706641, 6189744445, 2605712380, 6471811421, 5263854136, 5872030934, 6590302487, 5251271226, 6637491333, 2257589502, 5345640774, 2708476411, 7628391373, 1824523205, 7312770512, 5606738196, 1994394155, 6287264780, 2204109905, 6345985728, 2631929573, 3382710724, 2756710911, 5074064487, 5163188471, 2257586600, 2919238964, 3311403461, 7153385941, 7623148109, 3673162833, 1201670525, 5285876082, 6446649765, 7604274880, 7604275089, 7604277384, 7644120822, 7604275136, 7604278386, 3119514785, 7629439370, 7233082012, 6018826583, 2677019740, 5151656065, 5495588015, 7030706778, 7628395566, 5394924309, 7331647086, 1832915762, 6692014108, 6376392758, 7328500751, 5958012237, 3862957362, 5690626856, 6315578618, 6046091798, 5658116530, 5758783419, 7540310472, 7076839982, 1788870981, 2413823045, 1809843700, 5450500681, 5713694208, 6144660377, 6412047263, 7329550289, 7642027114, 6589254139, 2850033671, 2979005094, 6361712992, 5847912828, 2499806255, 5271192471, 5589959875, 6198137853, 7611614711, 5336208117, 5657070185, 6609174902, 5529143948, 6483349627, 7637828072, 2052064991, 5674896959, 7571768111, 5251272186, 1788871143, 6510612920, 7508856870, 2871005993, 7279215207, 1707083081, 2716862693, 5471471882, 5961158140, 3109031182, 3264221570, 3602910071, 2317358265, 2293236211, 1688212390, 6502223963, 7601132766, 7455378244, 1792017397, 6079645266, 6029314157, 5738858738, 6356470682, 2717912547, 3039826302, 3300918457, 6178210212, 7363102906, 5407507161, 5970593492, 7628392647, 6506417258, 6119490981, 6456083034, 5774510754, 5667556308, 2645560973, 2214593007, 6550455895, 6124733014, 5307893866, 7635731185, 7637828956, 7628391953, 1192235524, 2658142133, 5711596394, 5413798855, 3949989622, 6248464920, 6353324207, 5136977651, 2183140585, 5150606136, 7578062546, 5284828200, 2235564685, 7460620256, 5822745162, 6876563469, 5706351492, 7373587802, 7636779694, 3275754207, 6519002252, 5283775163, 5650777794, 5186260130, 7310672566, 5657068436, 6456085663, 6029313607, 7591691103, 5035267150, 2509246241, 3097495497, 3991932651, 5019536772, 7463764799, 5714742855, 2103447714, 6798972006, 2441087245, 5250220959, 7245660832, 7559185530, 6387929143, 6366958321, 5728371502, 5584717020, 3952084839, 5676993891, 7305432984, 5490347014, 6911168166, 3991931590, 6499079340, 7636782099, 5852103813, 5891950496, 3996125865, 5013245204, 7312769658, 7628391861, 7628392435, 2713717563, 2814380883, 5666505594, 6599738279, 5415896373, 5647632364, 5271194676, 7403998770, 6671043283, 1937772284, 6489637683, 6616516979, 6807359339, 5206183899, 5645538022, 6527386512, 2217742255, 3989835590, 6316623041, 3120565664, 5205135024, 2688550810, 5961157732, 5197793214, 3211789357, 6988763859, 3074425670, 2772439175, 6154097153, 7393513448, 5179968300, 6639585317, 3912240266, 7607422096, 5636097473, 3641706667, 1762657302, 6730810488, 7645172100, 7521440021, 7632587049, 6654264819, 7048531022, 2030044305, 7496271020, 5664412627, 7347373786, 7624200976, 7043286271, 1298140265, 2472544962, 6125785959, 6362760596, 2753562633, 1571819105, 5440017641, 1681917187, 5768220940, 7414482313, 5925504362, 7628394319, 2429552204, 5498737223, 3487566195, 5860495523, 7003440976, 6855591309, 6704596255, 5777657733, 5887757608, 7482639836, 3562014130, 6242174514, 6911165879, 5947526615, 5268049238, 5833231334, 6935286079, 7488931274, 5198843556, 5285873699, 6357517698, 3608153452, 5885658423, 5600446695, 7486837288, 3536848311, 5970594967, 6430921495, 7082084999, 5842667149, 7328500645, 2574255703, 6421482448, 5675944464, 5208281002, 6816797849, 6325012030, 2139097852, 7624197752, 5632952537, 5565846769, 7371492739, 7495223897, 5575281945, 7607421992, 6120539762, 7294945018, 6578770990, 6617566980, 7333744789, 2289045685, 7364151936, 5675944964, 3625977734, 7628393063, 5151655789, 7622100917, 6479154966, 5669654784, 5949622094, 5797580855, 7628395031, 3802140496, 6448746384, 5867835091, 6104814829, 5075109941, 7602178101, 5659166871, 6884955227, 5150607548, 5646584097, 2008025411, 5651828987, 7635732648, 6413093252, 7564429857, 7402949711, 7639927361, 6786387461, 6644830502, 2554334461, 7628394202, 7416580672, 5673849101, 6900683075, 6277828593, 5601496383, 6571429968, 5628760551, 6536825923, 7579110541, 6120542146, 6056578273, 6513757293, 5370809821, 7628393973, 6642732484, 7218400684, 5517610589, 1658850967, 5440017608, 6887051076, 5865738161, 6240079642, 6992957530, 7646220516, 6115299461, 2140147970, 5603594659, 3169849857, 7550800439, 2825916935, 2451575485, 6387929853, 1784681352, 3517977361, 2157974514, 7628395733, 2657096975], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 3, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 4, 2, 2, 6, 4, 2, 4, 2, 9, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 7, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 5, 2, 4, 5, 1, 3, 7, 6, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 2, 2, 1, 1, 2, 4, 4, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 4, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 3, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 3, 2, 1, 6, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 1, 10, 15, 18, 3, 6, 9, 6, 3, 18, 6, 3, 3, 18, 9, 15, 15, 3, 30, 9, 3, 9, 36, 9, 16, 9, 5, 2, 3, 4, 3, 2, 2, 3, 1, 1, 11, 2, 1, 1, 1, 2, 1, 2, 3, 1, 1, 2, 1, 1, 1, 3, 2, 2, 2, 6, 2, 2, 2, 6, 10, 2, 8, 4, 6, 4, 5, 6, 1, 3, 2, 1, 2, 2, 1, 2, 1, 1, 6, 3, 4, 1, 2, 3, 1, 12, 4, 5, 4, 3, 2, 3, 3, 1, 6, 2, 2, 2, 2, 2, 2, 4, 6, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 5, 2, 2, 3, 1, 7, 1, 1, 2, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 10, 6, 3, 7, 1, 1, 3, 1, 1, 1, 5, 4, 1, 1, 1, 2, 8, 7, 1, 1, 1, 2, 1, 5, 3, 1, 1, 1, 2, 4, 3, 1, 5, 3, 1, 1, 1, 1, 4, 3, 4, 1, 2, 1, 1, 2, 2, 4, 2, 4, 1, 1, 1, 2, 1, 1, 2, 3, 2, 3, 7, 4, 7, 1, 6, 5, 1, 2, 2, 1, 3, 2, 2, 1, 2, 4, 6, 1, 1, 1, 1, 1, 3, 2, 3, 1, 2, 4, 1, 6, 1, 3, 3, 5, 5, 1, 5, 1, 1, 1, 6, 4, 6, 2, 8, 27, 3, 2, 4, 1, 1, 1, 2, 4, 3, 4, 1, 3, 2, 2, 4, 5, 1, 1, 21, 2, 6, 4, 6, 4, 6, 8, 12, 4, 6, 10, 4, 12, 2, 2, 8, 2, 8, 1, 7, 10, 24, 2, 25, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 4, 5, 2, 2, 2, 2, 3, 3, 6, 3, 2, 2, 3, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 6, 2, 2, 1, 2, 1, 3, 1, 4, 1, 3, 1, 4, 8, 1, 1, 2, 3, 1, 2, 1, 2, 3, 4, 8, 2, 6, 2, 2, 14, 4, 1, 2, 2, 1, 8, 2, 2, 4, 8, 2, 2, 6, 1, 3, 1, 10, 2, 11, 2, 6, 1, 6, 6, 11, 17, 4, 2, 3, 5, 1, 1, 2, 1, 1, 2, 1, 5, 6, 7, 3, 2, 1, 3, 1, 1, 5, 6, 3, 3, 1, 1, 4, 1, 2, 1, 1, 5, 5, 9, 2, 2, 3, 1, 2, 1, 5, 5, 2, 5, 9, 1, 1, 8, 7, 9, 33, 1, 5, 2, 19, 2, 6, 6, 2, 5, 6, 5, 3, 1, 8, 3, 1, 8, 45, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 1, 7, 4, 1, 1, 1, 2, 1, 3, 1, 1, 2, 1, 2, 1, 4, 1, 1, 2, 1, 1, 2, 3, 1, 2, 11, 3, 5, 7, 9, 6, 3, 19, 5, 3, 7, 3, 10, 2, 2, 4, 2, 2, 17, 4, 4, 2, 4, 4, 4, 8, 16, 10, 10, 6, 10, 14, 4, 17, 1, 3, 4, 2, 8, 6, 3, 15, 3, 4, 3, 2, 2, 7, 1, 2, 1, 3, 4, 6, 1, 5, 10, 2, 4, 6, 2, 4, 7, 2, 4, 2, 1, 2, 5, 2, 1, 1, 1, 2, 3, 4, 2, 7, 7, 1, 1, 5, 7, 3, 1, 7, 12, 3, 5, 2, 7, 31, 3, 7, 7, 2, 6, 2, 5, 1, 1, 1, 7, 1, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 5, 9, 5, 8, 2, 1, 4, 11, 9, 1, 18, 1, 5, 20, 1, 16, 2, 27, 12, 3, 22, 9, 20, 2, 2, 3, 1, 2, 5, 

In [39]:
list_user,list_num = val_num(col)
df_makeup_num = pd.DataFrame(data=list_user,columns=['user_id'])
df_makeup_num

100%|███████████████████████████████████████████████████████████████████████████| 7254/7254 [00:00<00:00, 22423.99it/s]

         user_id
0     6387925087
1     5940184342
2     6046089267
3     6436159852
4     2839544222
...          ...
1390  1784681352
1391  3517977361
1392  2157974514
1393  7628395733
1394  2657096975

[1395 rows x 1 columns]

In [40]:
df_makeup_num['focus_makeup_num'] = pd.Series(list_num)           #每个用户关注美妆博主的数目
df_makeup_num

         user_id  focus_makeup_num
0     6387925087                 1
1     5940184342                 1
2     6046089267                 1
3     6436159852                 1
4     2839544222                 1
...          ...               ...
1390  1784681352                11
1391  3517977361                30
1392  2157974514                16
1393  7628395733                 1
1394  2657096975                 2

[1395 rows x 2 columns]

In [30]:
df_user_test

         user_id  focus_kol_num
0     7646220516             33
1     7645172196            135
2     7645172100             76
3     7645172015             41
4     7645169808             16
...          ...            ...
1989  1084229683             51
1990  1025509673             75
1991  1022362744             50
1992  1011876243             24
1993  1008733090             28

[1994 rows x 2 columns]

In [41]:
df_merge1 = pd.merge(df_user_test,df_makeup_num,on='user_id',
                    how='left',sort=False)                       #将用户关注的kol的数据与用户关注的美妆博主的数据merge
df_merge1

         user_id  focus_kol_num  focus_makeup_num
0     7646220516             33               8.0
1     7645172196            135               2.0
2     7645172100             76              11.0
3     7645172015             41               NaN
4     7645169808             16               NaN
...          ...            ...               ...
1989  1084229683             51               1.0
1990  1025509673             75               NaN
1991  1022362744             50               NaN
1992  1011876243             24               3.0
1993  1008733090             28               NaN

[1994 rows x 3 columns]

## 美食博主数目

- 导入文件 美食博主

In [42]:
df_food_kol = pd.read_csv('D:/datasets/qianyi/user_label/method/based_on_user_focusing_kol/file/food_kol_gt10w.csv',encoding='utf-8')
df_food_kol

,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con
0,5899491342,美食零食小吃货,0,m,安徽,合肥,6,·汉口学院98级,·情感公司2003年-2020年,2011-11-26,18920185.0,583.0,3969.0,商务合作：ok311331,作家 情感博主 微博原创视频博主,NaN,美食零食小吃货商务合作：ok311331nan作家 情感博主 微博原创视频博主
1,5889860264,郭诗妤Amarisbaby,0,f,上海,NaN,7,·厦门大学,NaN,1998-09-16,236727.0,148.0,137.0,淘宝：Amarisbaby. 店铺客服V:shiyu916111（客服3号美妞加） 工作...,NaN,"美食,美女,美容护肤",郭诗妤Amarisbaby淘宝：Amarisbaby. 店铺客服V:shiyu91611...
2,1606653640,Cream_Paul甜点教学,0,m,北京,NaN,7,NaN,·CREAM PAUL 甜品教学2011年-·北京国贸中心国贸三期酒店2010年-2011年...,NaN,192489.0,2801.0,3209.0,法国里昂西点世界杯中国赛区选拔赛冠军成员我叫PAUL 老婆叫CREAM 服务于有理想追求的甜...,美食博主 美食视频自媒体,"巧克力,拉糖,甜品教学",Cream_Paul甜点教学法国里昂西点世界杯中国赛区选拔赛冠军成员我叫PAUL 老婆叫CR...
3,6330267311,凌晨三点半来了,0,m,黑龙江,哈尔滨,2,NaN,NaN,1994-07-11,105636.0,418.0,408.0,你来，我就欢迎。,微博新知博主 互联网科技博主,"吃货,美食,篮球","凌晨三点半来了你来，我就欢迎。吃货,美食,篮球微博新知博主 互联网科技博主"
4,1302496952,如昨,0,m,福建,福州,7,NaN,NaN,01-01,265595.0,1374.0,8936.0,爱，就关注吧。即投缘，又缘何擦肩而过....对于福州历史典故，民俗、文化、方言、俚语、建筑、...,微博美食博主 超话粉丝大咖（投闽状超话）,"股票,登山看海,听歌",如昨爱，就关注吧。即投缘，又缘何擦肩而过....对于福州历史典故，民俗、文化、方言、俚语、建...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13542,6582920476,前线小面包,1,f,NaN,NaN,6,NaN,NaN,NaN,127660.0,509.0,1682.0,陪lmy走过漫长岁月.喜欢美食、旅行、读书🐰🐰,娱乐博主,NaN,前线小面包陪lmy走过漫长岁月.喜欢美食、旅行、读书🐰🐰nan娱乐博主
13543,6506168038,北京中诺口腔医院-种植中心,1,m,NaN,NaN,1,NaN,NaN,NaN,301255.0,431.0,408.0,北京中诺口腔医院，北京口腔医院、第四军医大专家团队，采用立得用种植牙体系，当天来院，当天种牙...,三级口腔医院，立得用数字化种植牙体系，当天种牙当天享美食！,NaN,北京中诺口腔医院-种植中心北京中诺口腔医院，北京口腔医院、第四军医大专家团队，采用立得用种植...
13544,3225618982,万达大歌星KTV长沙店,1,f,NaN,NaN,0,NaN,NaN,NaN,109373.0,1660.0,6409.0,大歌星KTV创立于2010年6月，是万达集团旗下的大型文化连锁企业，是集休闲娱乐、欢唱聚会、...,万达大歌星KTV长沙店,NaN,万达大歌星KTV长沙店大歌星KTV创立于2010年6月，是万达集团旗下的大型文化连锁企业，是...
13545,2378430134,伯爵先苼的家常美味,1,m,NaN,NaN,6,NaN,NaN,NaN,151720.0,233.0,2998.0,吃在路上ing、终身阅读者,携程社区签约旅行家 美食博主,NaN,伯爵先苼的家常美味吃在路上ing、终身阅读者nan携程社区签约旅行家 美食博主
13546,1804448601,木木-子-女闲,1,f,NaN,NaN,7,NaN,NaN,NaN,104387.0,440.0,1372.0,🌿美食、母婴博主 新手麻麻，BB:小粽子 记录体育老师和音乐老师一家的日常🌼,美食博主,NaN,木木-子-女闲🌿美食、母婴博主 新手麻麻，BB:小粽子 记录体育老师和音乐老师一家的日常🌼n...

In [43]:
df_m2 = pd.merge(df_ff,df_food_kol,left_on='followed_id',right_on='kol_id',how='inner')
df_m2

,_id,fan_id,followed_id,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con
0,6387925087_2809775704,6387925087,2809775704,2809775704,古茗茶饮,1,m,浙江,NaN,6,NaN,·古茗奶茶,0001-00-00,829350.0,70.0,2728.0,专注做品牌 只出好产品 每天一杯喝不腻,古茗茶饮官方微博,"美食爱好者,旅游美食","古茗茶饮专注做品牌 只出好产品 每天一杯喝不腻美食爱好者,旅游美食古茗茶饮官方微博"
1,3189768370_2809775704,3189768370,2809775704,2809775704,古茗茶饮,1,m,浙江,NaN,6,NaN,·古茗奶茶,0001-00-00,829350.0,70.0,2728.0,专注做品牌 只出好产品 每天一杯喝不腻,古茗茶饮官方微博,"美食爱好者,旅游美食","古茗茶饮专注做品牌 只出好产品 每天一杯喝不腻美食爱好者,旅游美食古茗茶饮官方微博"
2,6124733014_2809775704,6124733014,2809775704,2809775704,古茗茶饮,1,m,浙江,NaN,6,NaN,·古茗奶茶,0001-00-00,829350.0,70.0,2728.0,专注做品牌 只出好产品 每天一杯喝不腻,古茗茶饮官方微博,"美食爱好者,旅游美食","古茗茶饮专注做品牌 只出好产品 每天一杯喝不腻美食爱好者,旅游美食古茗茶饮官方微博"
3,5460987882_2809775704,5460987882,2809775704,2809775704,古茗茶饮,1,m,浙江,NaN,6,NaN,·古茗奶茶,0001-00-00,829350.0,70.0,2728.0,专注做品牌 只出好产品 每天一杯喝不腻,古茗茶饮官方微博,"美食爱好者,旅游美食","古茗茶饮专注做品牌 只出好产品 每天一杯喝不腻美食爱好者,旅游美食古茗茶饮官方微博"
4,6046089267_3178079602,6046089267,3178079602,3178079602,麻豆大佬,1,m,浙江,NaN,7,·浙江工业大学之江学院15级,NaN,1997-07-29,1718698.0,185.0,344.0,开开心心,抖音红人 时尚达人,"美食,les,T","麻豆大佬开开心心美食,les,T抖音红人 时尚达人"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10029,7628395733_1434414634,7628395733,1434414634,1434414634,叔大奥尼,2,m,上海,浦东新区,0,NaN,NaN,天蝎座,152282.0,1912.0,63947.0,话痨，哈哈哈刷屏警告。2只龙猫和1只橘猫的铲屎官。节操是啥？可以吃吗？,NaN,"美容,音樂,旅游美食","叔大奥尼话痨，哈哈哈刷屏警告。2只龙猫和1只橘猫的铲屎官。节操是啥？可以吃吗？美容,音樂,旅..."
10030,2183140585_3620315404,2183140585,3620315404,3620315404,白菜剁手菌,1,m,广东,广州,7,NaN,·白菜,1995-12-21,615787.0,887.0,65412.0,NaN,知名美食博主,搞笑幽默,白菜剁手菌nan搞笑幽默知名美食博主
10031,1880102027_1820731083,1880102027,1820731083,1820731083,消化科倔老头,1,m,江苏,苏州,6,NaN,NaN,1972-06-26,408721.0,465.0,9527.0,仗镜走天涯！,苏州大学附属第一医院消化科 副主任医师 刘强,"美食,旅游,电影","消化科倔老头仗镜走天涯！美食,旅游,电影苏州大学附属第一医院消化科 副主任医师 刘强"
10032,3195016464_3637060581,3195016464,3637060581,3637060581,JK-Jack,1,m,上海,NaN,6,NaN,NaN,1997-11-17,1020912.0,20000.0,10286.0,时尚播报员 、摄影师、方案策划、灯光师，需要合作或工作可加monster3355,时尚博主,"美食,旅游",JK-Jack时尚播报员 、摄影师、方案策划、灯光师，需要合作或工作可加monster335...
10033,7391417534_2149203924,7391417534,2149203924,2149203924,揾食珠三角,1,m,广东,广州,0,NaN,·广州广播电视台,01-01,998857.0,217.0,3330.0,广州广播电视台综合频道美食、生活资讯类栏目，每天17:40，每天5分钟，我们带路你班马，让你...,广州广播电视台栏目《揾食珠三角》官方微博,"全城来搜索,广州市电视台,揾食珠三角",揾食珠三角广州广播电视台综合频道美食、生活资讯类栏目，每天17:40，每天5分钟，我们带路你...

In [44]:
s_t = time.time()
col = df_m2['fan_id']
print(val_num(col))
print(time.time()-s_t)

100%|█████████████████████████████████████████████████████████████████████████| 10034/10034 [00:00<00:00, 22254.29it/s]

([6387925087, 3189768370, 6124733014, 5460987882, 6046089267, 6527385758, 5827986408, 7441744973, 5632951476, 5774510754, 6326059017, 6369053134, 5232394439, 2773483781, 6994002194, 5932843301, 3311403461, 5581570970, 5598348323, 5428479062, 5674894611, 5797578181, 7541360362, 6264194792, 2175796887, 5754586756, 3779069470, 3082815103, 5247076073, 5369759455, 5658117986, 2688550810, 2977958254, 2204109374, 5832182518, 7497321292, 7483689881, 7172262742, 3912240266, 7093619939, 1761611080, 6590303572, 7632588202, 3164606267, 6264197020, 3923775503, 5206183899, 5539631152, 6394220713, 5164241149, 6066016517, 1923092867, 7628395079, 5127541302, 6030365239, 3843035609, 5770318606, 5458891328, 5653926743, 5854205015, 6534730702, 5834282011, 7089427548, 5980034161, 5872030934, 7225737229, 5473568092, 6069159514, 1734346281, 3830451205, 6642732484, 2683309400, 5947526615, 5252321071, 3713012290, 6742348497, 3404726320, 5887754455, 7411335497, 3991929413, 2979005094, 6879707995, 1840251830, 5128586383, 5970593492, 7645169599, 5661263589, 5151656065, 6564088108, 2491419087, 2182089402, 5452598241, 7331647086, 5622468666, 6024073983, 7635730588, 5238686271, 2560624342, 2872051450, 3964667456, 6876563469, 6894389775, 5911874525, 5018488122, 6448746160, 5596253758, 1869615411, 6318723373, 5284828200, 5435818162, 7297040450, 6825181252, 2265973147, 5836374534, 7442793105, 5754585870, 6631196524, 6577719301, 5606738196, 6536825923, 6556749820, 6369054924, 5548019883, 7458525615, 6575625356, 5663364326, 6224347379, 1815087072, 7022313660, 7626293803, 6539969232, 5832180305, 5407507161, 5375001458, 3210740461, 2138047350, 6871319321, 5721031690, 6174016598, 1842349087, 2619343925, 1915749445, 7312770512, 2429552204, 6242174514, 6120539762, 5650777794, 6526338826, 2052064991, 3322939110, 2088765381, 5025826695, 7281313841, 7313819539, 7368345778, 5600446695, 5381294573, 5851056653, 1767901820, 6052383483, 6664751958, 6398413748, 3030387813, 7626296615, 7139757500, 3122662885, 5961158140, 2717912547, 1658850967, 6790581955, 2936016687, 2300579663, 5208281002, 5896146920, 3784314995, 6476009557, 2708476411, 2969572061, 7195333285, 6125785959, 2236617681, 3197113400, 7601132766, 7505712217, 3289382982, 6590302487, 5719987169, 7157579841, 7423918281, 6366953899, 7556039125, 6222250501, 2435842357, 2030044305, 7333742078, 2132805171, 6904874707, 5632952537, 7408192118, 5517610589, 6085938828, 5867835091, 7365726235, 5971644741, 2614104831, 7626298350, 5887754401, 5756682481, 3862954213, 5951717676, 6189744445, 6530531801, 6157238908, 7270826540, 7020217029, 6232736401, 6524240742, 7323255687, 1762657302, 6512706641, 5584717020, 7099909347, 3349152972, 7611614711, 6111102557, 7510951797, 7640975353, 5883561859, 7457474396, 5873076491, 7629441123, 2969569491, 6361712992, 7563381071, 7169116486, 7550798157, 7629441462, 5185210739, 7495223897, 7494175286, 3958377014, 5272242868, 7642024672, 2124417800, 7316966133, 7564430201, 7610567583, 7642024895, 6575623130, 2907704435, 5601496383, 6361714093, 6334451147, 6228545185, 7531925151, 6161436588, 5797580855, 1736446333, 6928994774, 7565480550, 7463768762, 1832915762, 5020586705, 6880760885, 7391417534, 6519002252, 7014973647, 7076839982, 5613029546, 5042604297, 6085935235, 7642022289, 5714739763, 1808794634, 5982127416, 5243930053, 2889876973, 1642071512, 7645169378, 7075793083, 2410678723, 7642024683, 6506417258, 7471108141, 6383735194, 2247103173, 5579477772, 6210720559, 7371490073, 1422919762, 1213205403, 1805651092, 5648682214, 2949648261, 2391805985, 3187671341, 7279215089, 5579473603, 7326401389, 1980760857, 5657068436, 5826937883, 7195329816, 1854932363, 2290091540, 7624197752, 5842667149, 5879367454, 7422871383, 7585400606, 1175455614, 6430918573, 7460620256, 5575280697, 1914701893, 5233445025, 7363102875, 5496637586, 6107957607, 6920604029, 6599739871, 5529143948, 6800018145, 6786386931, 1298140265, 7212108927, 5019536772, 7498370548, 7578062546, 5627711160, 6442454734, 7210012534, 6334451537, 6120542146, 6791630823, 6483349627, 7400853632, 1192235524, 7458525915, 6852448995, 7634686851, 5894050662, 5664412627, 5470425986, 6642734098, 6578770990, 5440017608, 7150245104, 2232423695, 6311379010, 1664092063, 6354370706, 5031067758, 6282019086, 6343885545, 3097495497, 5237639112, 7122978875, 3508537641, 6347033762, 5954866406, 2316307877, 6144660377, 7604273163, 7604273655, 7604273695, 7604273780, 7604274704, 7604274748, 7604274880, 7604275136, 7604275381, 7603226927, 7604275604, 7604275681, 7604275957, 7604277384, 7604278013, 7604278159, 7604278386, 7604278546, 7604273561, 7604273797, 7604274094, 7604274347, 7604274457, 7604274858, 7604274963, 7604275120, 7604275502, 5499783647, 7604275904, 7604276166, 5682236430, 7604277820, 7499420500, 7466914710, 7604275359, 7604275633, 7604276333, 6081742342, 2291140935, 7418678764, 7432310536, 3862958192, 6611276122, 7485784241, 3862954252, 6802113819, 6704596255, 6924798334, 5846862798, 7569673593, 5933895293, 7569674236, 7505711271, 5667558635, 7635730546, 7523533021, 7076839703, 6590300614, 5391778241, 6456083034, 5152703125, 6029313326, 7264536028, 2014316040, 6311380563, 5554308702, 6174017297, 5738858357, 5307893866, 2297432151, 6522145084, 6046091798, 1840253470, 1994394155, 5733616430, 5593107511, 6450842867, 6345985728, 6315577078, 5205134941, 1967132721, 5842670010, 5645537695, 7488934587, 7416583176, 6700405855, 3186627844, 6663700515, 1022362744, 5023728191, 7401899306, 6547310608, 6461327551, 2351958277, 3128953532, 2205159330, 2713718575, 6644830429, 3047167045, 7025464442, 6208618670, 5468324221, 7384072804, 7291800090, 7574915375, 3061844741, 7357860946, 2509246241, 5389684751, 3862958343, 6376390686, 3109031182, 7604273273, 7604273451, 7604275089, 7604277205, 7604274348, 7604274585, 7604274762, 7604274908, 7604275115, 7604275813, 3199206421, 3487566195, 5250222950, 6491736954, 2814380883, 5285876082, 5888807807, 6499079340, 7548698761, 6536827265, 5748293791, 6612320717, 7373587802, 7344228971, 5284827646, 2672820597, 5601493566, 6464472922, 3720349827, 7639927361, 5822745162, 5627711787, 5651828987, 2170557313, 3896513652, 2708471847, 3972007841, 1740640480, 2087716404, 5746199970, 6413095099, 2763003071, 7508856870, 7406097608, 7514096990, 7338985685, 7507808992, 2582643692, 7530874790, 6035607368, 6274683008, 6441406558, 2683306062, 7571767513, 2879390664, 1660945571, 5495588015, 5383392119, 5970594967, 6426722667, 3104834245, 1989149391, 6316622807, 1913652445, 5949622094, 3588229930, 5680139067, 1951403167, 3174043831, 6169825683, 1734349565, 6322918520, 2257589502, 2605712380, 6125782321, 6325012030, 6331303607, 5271193630, 6353324207, 5711596394, 5362420848, 5676993891, 7552896770, 6472863943, 6202331280, 7629439370, 7543460627, 6436160166, 1586496603, 3547333734, 5589959730, 6322914534, 5538579847, 5372904897, 6111103253, 3232762284, 7458523672, 5399120418, 5045750386, 2472544962, 5842668219, 5370809821, 5656022758, 5541727999, 5082451866, 6571429968, 7282361302, 5469375785, 7218400684, 6477055322, 3860858986, 7559186572, 7364151936, 2462058965, 5833231334, 5971643562, 1785728405, 5638197818, 7203717520, 5170529428, 5885658423, 5729423135, 3382710724, 5422186502, 7368345989, 5451550868, 2258637334, 3517977361, 6555701903, 5861540841, 6196037626, 5618272410, 3991932651, 3843031220, 5345640774, 5304746434, 7314866859, 5611979338, 2687500891, 2523923167, 5972689643, 1864368784, 5270143835, 7640974742, 6272583185, 6235883066, 5050992294, 1951401805, 5151655789, 5971642294, 5647632364, 6656362641, 2716862693, 6335498637, 2848983611, 5352983131, 5480909318, 6270487112, 5656021626, 7622101773, 3275754207, 5186260130, 5603593370, 6033510197, 5172629522, 6236934142, 2850033671, 1863323773, 1950355587, 1751126254, 5669654784, 5847912828, 5603594659, 7438602422, 7337939331, 5498737223, 5683286636, 2133857160, 3840938852, 5845816433, 5035267150, 2317358265, 5285876949, 6442451658, 2629829335, 7405044926, 7540312315, 3502246103, 5980031628, 2010122961, 6502223963, 7530877342, 6524244361, 7452234321, 2674922390, 6798972006, 5856298170, 6459229757, 7457475067, 5675945051, 6485445863, 7408193448, 3167748210, 5939134550, 5362417762, 5658116530, 6609174902, 5969543775, 5692719806, 6300893880, 6077547270, 6218056544, 6587155325, 5589959875, 1774191811, 7636780417, 6053430506, 3516925327, 3887072746, 6069159580, 6312429331, 5976884928, 5986322238, 2500855794, 5275387803, 7479494846, 5033167093, 5471471882, 1025509673, 6629099969, 5713693173, 7029656135, 5251271226, 5574232906, 5831133959, 5531241664, 3920628978, 5528095839, 7573867910, 2140147024, 3949989622, 6433017578, 6261051364, 5645537365, 7626297502, 7273975949, 5815406834, 6006247838, 5646586481, 6584013349, 5992616452, 2394952295, 5851058886, 2319455050, 5690626856, 5520757602, 7584355160, 5825893273, 3992982524, 7313817728, 6144656141, 2718958351, 6934234084, 5980030384, 1809843700, 5075109941, 1084229683, 5457840507, 5948572200, 3015705561, 7310676228, 7559185530, 7345277767, 5575283343, 5969548025, 5721035541, 5818548240, 5663360627, 2350907602, 7642022104, 5609881782, 7129268707, 7153385941, 2413823045, 3189769312, 6570378470, 7405045086, 7637828956, 7631537614, 5415896373, 7631537646, 6855591309, 3533702952, 7566527148, 7628393207, 5961157343, 6264195870, 2006977311, 2407533263, 7455378244, 2670726003, 6163532738, 6547311648, 7636782100, 6333402571, 1901072083, 7558139690, 7500468199, 5225058344, 7551848606, 6083842239, 7520391386, 6791631129, 7486837049, 2606764293, 7355765284, 6056579722, 1846546933, 7406097279, 7642027114, 7530878006, 7388271689, 7604273248, 7604274179, 7604274745, 7604277903, 7604277885, 7604274884, 7604276663, 7604277213, 6178210212, 6085936374, 6138368196, 5471471505, 2182086854, 6447694094, 1823473980, 5455741380, 5666505594, 5206181359, 7294945018, 5197793214, 5053090142, 5035264454, 2919238964, 5660218032, 7628390711, 5714742855, 5179968300, 7403998164, 2965377983, 7604274594, 7604276244, 2864710142, 6122637739, 6988763859, 7604275372, 6600786489, 3211789357, 1764754532, 7363102906, 7403998770, 6240079642, 6287263809, 2033191457, 7328500751, 6385831395, 3127906317, 5250224781, 5496635584, 1785727537, 2139097852, 7550799014, 3608150120, 3035629497, 5953814760, 5658117260, 7104103727, 3641706667, 2925529160, 7458523696, 7631538828, 2095057550, 2337279007, 5860495523, 5927600385, 5107614763, 5629806017, 3818915327, 7111444792, 6636440769, 7636782265, 6002053152, 7550800439, 6671041379, 6730810488, 7564429857, 7276072701, 7472157518, 2554334461, 7582254323, 7645172196, 5632950445, 5663360519, 7642024849, 3568306760, 6319772102, 7604276215, 5077210273, 5997858891, 7604277244, 7604277277, 6222252165, 6270484632, 1870660163, 7628393063, 3625975950, 2690646624, 7482639836, 2713717563, 2289045685, 5995760926, 3686796512, 3169849857, 7604274507, 5756686270, 6029313607, 6570381707, 7043286271, 5015342949, 7628395566, 6632245084, 5664410440, 6637491333, 5847909489, 3862957362, 5394924309, 6117393738, 7384073675, 3625977734, 7220496290, 2291142255, 2753562633, 3039824127, 2291140720, 6236932529, 7374637783, 1747980831, 6176117621, 2897216585, 6193942531, 6884955227, 3285189135, 1797261550, 2441087245, 3639609973, 5837425401, 3308260391, 3120565664, 3896512202, 5747250002, 1114641421, 7380930640, 5201988585, 5865737342, 5268049238, 5247078421, 2658145312, 3339719780, 6316623041, 6349128075, 2694841300, 2642413341, 6234835960, 6480204176, 7335842171, 6627005196, 7563383889, 2557476982, 3926917726, 6042944349, 1756366277, 2008025411, 2293236211, 7323256282, 5804921027, 6530531457, 7642024427, 5625610669, 6267339662, 6568282208, 5646584097, 6513757293, 6387929143, 6104814829, 6654264819, 6198137146, 5646581984, 1940915945, 6442452990, 1674578333, 7216302594, 3631221883, 3264221570, 5638198131, 5744100612, 6174017485, 2614102482, 6246367661, 5724176988, 5898240773, 6601835577, 5529142272, 5334107245, 5894047089, 5538580281, 1799358551, 7499417860, 5247077675, 2651852633, 5910827046, 5991567497, 6468669797, 7373590932, 6019879576, 5664412340, 5623518229, 6351230076, 3041919821, 1583353113, 5403316210, 2415924044, 3074425670, 6321869710, 1955594463, 5970592373, 6463426793, 2112881787, 6074402623, 5947525526, 6427774450, 5701111678, 2889875755, 1969226473, 1201670525, 6263144683, 6808404609, 6028263512, 5307892121, 5349835872, 5797577836, 7356811268, 7632586775, 5299505779, 1873808150, 5344594714, 6441405473, 6287264780, 6437211342, 5205135024, 7631540088, 6504321268, 5249176076, 3802140496, 7628390817, 7628394985, 7030706778, 7628395477, 2677019740, 3544190264, 7642022778, 7614762327, 7590645119, 7444893312, 6071259551, 7003440976, 3251634692, 5932846437, 7207914728, 6266294637, 5045748838, 5392828865, 5795481207, 5015340350, 5768220940, 2873098245, 6480199897, 5758783419, 5163188471, 7540310472, 5784995661, 3183480684, 7623148109, 2130707327, 3536848311, 6214910802, 6517949986, 6618615434, 2353004795, 7358911176, 6412047263, 6816797849, 5492445904, 6081742463, 5972692668, 7499419787, 7346323836, 2708474711, 5632955414, 7443845384, 3209696452, 6298797876, 2630878293, 5049944305, 5769269460, 7628391737, 5507122551, 7636782099, 7645172100, 7630491031, 2585792442, 7496271020, 3300918457, 6413093252, 5013245204, 5523900395, 6097469742, 2119176290, 6479152153, 5738858738, 1916800575, 7609520282, 2908754875, 3746562813, 5657070185, 7032800224, 7471106591, 7595887227, 1833962342, 5251272186, 5865738161, 6154097153, 6017780096, 5840571192, 7642022260, 5283775163, 5729420103, 6131025568, 6380587566, 6618615204, 5198843556, 5937041235, 5915021784, 6486495624, 6366958321, 5674894050, 5217719473, 7212105986, 7212106069, 7212106219, 7212106402, 7212106413, 7212107077, 7212107185, 7212107356, 7212107555, 7212107610, 7212107748, 7212107796, 7212107922, 7212108498, 7212108607, 7212108754, 7212108863, 7212109185, 7212109269, 7212109875, 7212110112, 7212110196, 7212110356, 7212110348, 7212110964, 7212111067, 7212106329, 7212106488, 7212108399, 1870661961, 6426727660, 5398069540, 1241515251, 3711964280, 5642391131, 5707399667, 5652873504, 5216665900, 5269097477, 7603228315, 5170531633, 7325356464, 2271215917, 2658142133, 7565479590, 7174361896, 5271192471, 7384074987, 5688526469, 7581204764, 6039799688, 1577060963, 2474639661, 5768220995, 7642022331, 7400850596, 7486834152, 7455377634, 7590644139, 7545555613, 7642024899, 7532973367, 6424630337, 1883242757, 7310672566, 6529485447, 5988419288, 6914315484, 6826230327, 7644120822, 5645534996, 2687504397, 1858079142, 6671043283, 2500857735, 2825916935, 5717889963, 7635732006, 7212106294, 7212108230, 7212108346, 7212109569, 7212109763, 7212109788, 7212109872, 7212110584, 7212110566, 7212110806, 7212110867, 7212110799, 7212106591, 7212106633, 7212106650, 7212106810, 7212106851, 7212107697, 7212107870, 7212108988, 7212109240, 6267341785, 5777657733, 5263854136, 2645560973, 3506440315, 3549432361, 6558844878, 5096079693, 7632587608, 5848957433, 7591691103, 3368031092, 1795163750, 6345983774, 7523537096, 2545943802, 3520069934, 1605372527, 2280653301, 1011876243, 7406096360, 7603229768, 7542407573, 7487883528, 5336208117, 6372200491, 6240077430, 7281313574, 6969888979, 6855594849, 6092227916, 6326061700, 6430921495, 5839524538, 2499806255, 6434067197, 6056578273, 6436159852, 5893001004, 7628395031, 7627346460, 7245660832, 5490347014, 5993663875, 1937772284, 6363808170, 6018826583, 1815086872, 6900683075, 5675944964, 7504658765, 6886000071, 1838153970, 2752513311, 5713694208, 5591011722, 6896487225, 1670385374, 1571819105, 5888804628, 7602178101, 5974789180, 7416580672, 2163213213, 7646220516, 5658121111, 1788870981, 3748659643, 5585765537, 6898584291, 5193599721, 2160070602, 5212471711, 1688212390, 5992612340, 6620710629, 7408194082, 5201989332, 7029655694, 6387929853, 5150607548, 5674896959, 5652874874, 6284120141, 7542407613, 3955232028, 7304385634, 7637828072, 6420432869, 6512705897, 6458181428, 7628392877, 5520756459, 7312769658, 7409238941, 3919581437, 5671752404, 3195014850, 2661287101, 7203719967, 7204770366, 7212110665, 2920287835, 6457135539, 2920285180, 6142560165, 6070207544, 6277828211, 5648683885, 5692719548, 7330595567, 1678771360, 5857349467, 6486495854, 7189040030, 7622100917, 3039826302, 3386904404, 5465179441, 7403996213, 3952084839, 6589254139, 6277828593, 5129637949, 5848961936, 1847596171, 6474962178, 5671749879, 7607421992, 6935286079, 5244981846, 2011169162, 2508196815, 6465523220, 5636097473, 6456085663, 3963622624, 3180332004, 6125783643, 2214593007, 7467962514, 7632586675, 5976883513, 5891950496, 6911168166, 7645169808, 6248464920, 6032461856, 5667556308, 7017073888, 2116030091, 7329550289, 2871005993, 2839544222, 5774510889, 6574575950, 7625245573, 3836744110, 5650780703, 5628756545, 3909095811, 7194283797, 2614104683, 2863662047, 5652873820, 5628756560, 2424312563, 6329206444, 6604981263, 6362760596, 3085961801, 2194673857, 6619661213, 6029314157, 5980030242, 2054162565, 5347741001, 1846546614, 3138393303, 6241128371, 7305432984, 6093278516, 7279215207, 1871709072, 5714740890, 5285873699, 6527386512, 7633637419, 7438598778, 2671774151, 5635049624, 5997859786, 2235564685, 6637487520, 7635731185, 7616858557, 5706351492, 1831862814, 5446304360, 2756710911, 7636779719, 7607422096, 2421164870, 5938087995, 6762271582, 2134903467, 5940185433, 7632587049, 7632587735, 7549750088, 5136977651, 5866788048, 7512002058, 5961157732, 5493492918, 5249173489, 5653923651, 7314868714, 6473913308, 5873074920, 6431969510, 7433356067, 6992957530, 5810160406, 7320113051, 5958012237, 2217742255, 5861543314, 5954867064, 7628391203, 6246369366, 6012538477, 5227155200, 2958034731, 6935286022, 3124757303, 5728371502, 6385828617, 7628391307, 5469373217, 2583696274, 7463764799, 5239738044, 6448746384, 7400850194, 6599742133, 3506443320, 6570378335, 2204109905, 2980054561, 5874125789, 3996127977, 7347373786, 2103447714, 7632587434, 7233082012, 1824523205, 5531239280, 2102396423, 5728371643, 6592400769, 3608152194, 6079645266, 5658117743, 5228203714, 6271534859, 6067061803, 7213155309, 6644830502, 6304041513, 6076498988, 5637148943, 7048530968, 7499419432, 5727326082, 5938087938, 6421482448, 5536484932, 6807357351, 5250220959, 5243929701, 7495222356, 7438603436, 7305431836, 5969546948, 7569672144, 6509561734, 7226787069, 5440017641, 6206523054, 1880102027, 2298479943, 3994028037, 6737105571, 5210378563, 5925504362, 1681917187, 7628391867, 6339695805, 3562014130, 6200233992, 6550455895, 5286922720, 3989835590, 1707083081, 6315578618, 2042627520, 6587158738, 5416945667, 6372201019, 6357517698, 3608153452, 3218081713, 6329209475, 6897534435, 5071964119, 5541725553, 7628394600, 6115299461, 6091179521, 6309283331, 6508513204, 7328500645, 7361005530, 7628391953, 6037705673, 7313822940, 7596935684, 7628392045, 5229252944, 7500467393, 5778703984, 2887781772, 7203721440, 3659533371, 2055210655, 5216670127, 6532630116, 6262099114, 5233446625, 6903826121, 7640975074, 7408194016, 3168798325, 7366249165, 7272924982, 7628392259, 3602910071, 7330596604, 7632586639, 7624200413, 3996125865, 5887757608, 5170531018, 7628392435, 3120566062, 7386171414, 6639585317, 5047849079, 7635732648, 2483032267, 7611616568, 5969545509, 5336206779, 7628394328, 7521440021, 6387930240, 6585059808, 6246369997, 5565846769, 2451575485, 7082084999, 3319795330, 6414143105, 5575281945, 3169848180, 2149585017, 6029314979, 2150634264, 6759124052, 7628393612, 5271194676, 2657096975, 7364152451, 7159680283, 7318015330, 6198137853, 1998589292, 6331305631, 3309309371, 7003442657, 2697991422, 7369395751, 1784681352, 6501174992, 3833597455, 7307529741, 6479154966, 7393513448, 7069503353, 6449794961, 5863641295, 5824844113, 1934627235, 7384076683, 5208282407, 5336207850, 5628760551, 6209671789, 6501175944, 3162510074, 7548703384, 7634686771, 7628395311, 1765806863, 5170533386, 6265246749, 6486496508, 2183140585, 7628395800, 7628395733, 3195016464], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [46]:
list_user,list_num = val_num(col)
df_food_num = pd.DataFrame(data=list_user,columns=['user_id'])
df_food_num['focus_food_num'] = pd.Series(list_num)
df_food_num

100%|█████████████████████████████████████████████████████████████████████████| 10034/10034 [00:00<00:00, 20499.55it/s]

         user_id  focus_food_num
0     6387925087               1
1     3189768370               1
2     6124733014               1
3     5460987882               1
4     6046089267               1
...          ...             ...
1648  6486496508              11
1649  2183140585               1
1650  7628395800               2
1651  7628395733               3
1652  3195016464               2

[1653 rows x 2 columns]

In [47]:
df_merge1

         user_id  focus_kol_num  focus_makeup_num
0     7646220516             33               8.0
1     7645172196            135               2.0
2     7645172100             76              11.0
3     7645172015             41               NaN
4     7645169808             16               NaN
...          ...            ...               ...
1989  1084229683             51               1.0
1990  1025509673             75               NaN
1991  1022362744             50               NaN
1992  1011876243             24               3.0
1993  1008733090             28               NaN

[1994 rows x 3 columns]

In [48]:
df_merge2 = pd.merge(df_merge1,df_food_num,on='user_id',
                    how='left',sort=False)
df_merge2

         user_id  focus_kol_num  focus_makeup_num  focus_food_num
0     7646220516             33               8.0             9.0
1     7645172196            135               2.0            46.0
2     7645172100             76              11.0             7.0
3     7645172015             41               NaN             NaN
4     7645169808             16               NaN             8.0
...          ...            ...               ...             ...
1989  1084229683             51               1.0             1.0
1990  1025509673             75               NaN             2.0
1991  1022362744             50               NaN             5.0
1992  1011876243             24               3.0             4.0
1993  1008733090             28               NaN             NaN

[1994 rows x 4 columns]

## 旅行博主数目

- 导入文件 旅行博主

In [ ]:
# df_travel_kol = pd.read_csv('D:/datasets/qianyi/user_label/method/based_on_user_focusing_kol/file/travel_kol_gt10w.csv',encoding='utf-8')
# df_travel_kol

# df_m2 = pd.merge(df_ff,df_travel_kol,left_on='followed_id',right_on='kol_id',how='inner')
# df_m2

# s_t = time.time()
# col = df_m2['fan_id']
# print(val_num(col))
# print(time.time()-s_t)

# list_user,list_num = val_num(col)
# df_travel_num = pd.DataFrame(data=list_user,columns=['user_id'])
# df_travel_num['focus_travel_num'] = pd.Series(list_num)
# df_travel_num

# df_merge2

# df_merge3 = pd.merge(df_merge1,df_food_num,on='user_id',
#                     how='left',sort=False)
# df_merge3

In [49]:
df_travel_kol = pd.read_csv('D:/datasets/qianyi/user_label/method/based_on_user_focusing_kol/file/travel_kol_gt10w.csv',encoding='utf-8')
df_travel_kol

,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con
0,3263402975,我是CHLOE,0,f,上海,NaN,6,·华东理工大学,NaN,2000-03-01,228408.0,458.0,577.0,旅行玩家，去过五十几个国家,NaN,"穿衣美容,投资理财","我是CHLOE旅行玩家，去过五十几个国家穿衣美容,投资理财nan"
1,5014296291,婀娜多姿拉拉,0,f,陕西,NaN,7,NaN,NaN,NaN,1048394.0,7753.0,32482.0,旅行，只有起点，没有终点。,知名旅游博主 去哪儿网聪明旅行家 超话粉丝大咖（小脚丫走世界超话） 微博故事原创作者 旅行视...,NaN,婀娜多姿拉拉旅行，只有起点，没有终点。nan知名旅游博主 去哪儿网聪明旅行家 超话粉丝大咖（...
2,5606936822,自然卷_卷卷,0,f,新疆,乌鲁木齐,4,·陕西中医药大学10级,NaN,1996-01-02,218714.0,101.0,161.0,还在努力的一名混干皮 看似温柔实则沙雕 喜欢摄影 热爱旅行 日常种草：护肤｜美妆｜生活好物...,旅游博主 微博原创视频博主,"摄影控,护肤,喜欢旅游",自然卷_卷卷还在努力的一名混干皮 看似温柔实则沙雕 喜欢摄影 热爱旅行 日常种草：护肤｜美...
3,2358288921,小小攻略菌,0,f,内蒙古,NaN,6,·澳门旅游学院11级·澳门旅游学院04级·澳门旅游学院,·九零后旅行社2009年-2015年,1992-07-06,446322.0,2044.0,2177.0,旅拍中国，打卡小众景点，享受自由行带来的舒心旅行！,旅游博主 马蜂窝攻略作者,"成都生活,旅遊,爱自由","小小攻略菌旅拍中国，打卡小众景点，享受自由行带来的舒心旅行！成都生活,旅遊,爱自由旅游博主 ..."
4,1686128307,紫荆__,1,f,天津,河西区,6,NaN,NaN,NaN,1247566.0,628.0,24669.0,专栏作家、旅行玩家、美妆达人；weix：lljing2010,时尚达人 乐途旅游网特约旅行家 旅游体验师 同程旅行推荐官 知名旅游博主 头条文章作者,"自驾,旅游,嘉人美妆精英","紫荆__专栏作家、旅行玩家、美妆达人；weix：lljing2010自驾,旅游,嘉人美妆精英..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17339,5915608851,陕西逗姐,1,f,NaN,NaN,4,NaN,NaN,NaN,205188.0,2181.0,2709.0,爱生活 爱旅游,旅游博主,NaN,陕西逗姐爱生活 爱旅游nan旅游博主
17340,5533452867,彩云天上飘,1,f,NaN,NaN,6,NaN,NaN,NaN,152836.0,5033.0,12406.0,喜欢在旅行中带来的快乐～,旅游博主,NaN,彩云天上飘喜欢在旅行中带来的快乐～nan旅游博主
17341,5393185738,酷酷滴小峰哥,1,m,NaN,NaN,1,NaN,NaN,NaN,128459.0,726.0,706.0,NaN,旅游博主,NaN,酷酷滴小峰哥nannan旅游博主
17342,1426709441,I赤龙飞天I,2,m,NaN,NaN,6,NaN,NaN,NaN,143783.0,2005.0,2736.0,爱旅游 爱摄影 爱交天下朋友；,NaN,NaN,I赤龙飞天I爱旅游 爱摄影 爱交天下朋友；nannan
17343,2964369403,美术渣渣Wei,1,f,NaN,NaN,7,NaN,NaN,NaN,108910.0,337.0,3208.0,嘘！！！好运来了。,旅游博主,NaN,美术渣渣Wei嘘！！！好运来了。nan旅游博主

In [50]:
df_m2 = pd.merge(df_ff,df_travel_kol,left_on='followed_id',right_on='kol_id',how='inner')
df_m2

,_id,fan_id,followed_id,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con
0,6387925087_2809775704,6387925087,2809775704,2809775704,古茗茶饮,1,m,浙江,NaN,6,NaN,·古茗奶茶,0001-00-00,829350.0,70.0,2728.0,专注做品牌 只出好产品 每天一杯喝不腻,古茗茶饮官方微博,"美食爱好者,旅游美食","古茗茶饮专注做品牌 只出好产品 每天一杯喝不腻美食爱好者,旅游美食古茗茶饮官方微博"
1,3189768370_2809775704,3189768370,2809775704,2809775704,古茗茶饮,1,m,浙江,NaN,6,NaN,·古茗奶茶,0001-00-00,829350.0,70.0,2728.0,专注做品牌 只出好产品 每天一杯喝不腻,古茗茶饮官方微博,"美食爱好者,旅游美食","古茗茶饮专注做品牌 只出好产品 每天一杯喝不腻美食爱好者,旅游美食古茗茶饮官方微博"
2,6124733014_2809775704,6124733014,2809775704,2809775704,古茗茶饮,1,m,浙江,NaN,6,NaN,·古茗奶茶,0001-00-00,829350.0,70.0,2728.0,专注做品牌 只出好产品 每天一杯喝不腻,古茗茶饮官方微博,"美食爱好者,旅游美食","古茗茶饮专注做品牌 只出好产品 每天一杯喝不腻美食爱好者,旅游美食古茗茶饮官方微博"
3,5460987882_2809775704,5460987882,2809775704,2809775704,古茗茶饮,1,m,浙江,NaN,6,NaN,·古茗奶茶,0001-00-00,829350.0,70.0,2728.0,专注做品牌 只出好产品 每天一杯喝不腻,古茗茶饮官方微博,"美食爱好者,旅游美食","古茗茶饮专注做品牌 只出好产品 每天一杯喝不腻美食爱好者,旅游美食古茗茶饮官方微博"
4,5138022423_2700162334,5138022423,2700162334,2700162334,逍遥散人M,1,m,其他,NaN,7,NaN,NaN,1990-02-05,3570623.0,511.0,4864.0,做视频的，希望大家天天开心！ 工作联系邮箱xysrgames@126.com,前 新浪看游戏人气主播；燃烧吧大脑100强 游戏视频自媒体,"游戏,旅游","逍遥散人M做视频的，希望大家天天开心！ 工作联系邮箱xysrgames@126.com游戏,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9190,3195016464_3637060581,3195016464,3637060581,3637060581,JK-Jack,1,m,上海,NaN,6,NaN,NaN,1997-11-17,1020912.0,20000.0,10286.0,时尚播报员 、摄影师、方案策划、灯光师，需要合作或工作可加monster3355,时尚博主,"美食,旅游",JK-Jack时尚播报员 、摄影师、方案策划、灯光师，需要合作或工作可加monster335...
9191,7604278546_3500331105,7604278546,3500331105,3500331105,兴趣星闻,2,m,内蒙古,呼和浩特,0,NaN,NaN,NaN,567133.0,5004.0,7379.0,如果梦里有你，我马上入睡！,NaN,"旅游,文艺","兴趣星闻如果梦里有你，我马上入睡！旅游,文艺nan"
9192,7391417534_1644869312,7391417534,1644869312,1644869312,半张碟,1,m,北京,NaN,5,·中央戏剧学院,NaN,0001-00-00,304131.0,677.0,7715.0,别停。,编剧柳桦,"旅行,电影","半张碟别停。旅行,电影编剧柳桦"
9193,2232423695_1825021343,2232423695,1825021343,1825021343,迪拜-24,1,m,海外,其他,7,NaN,NaN,01-01,679273.0,791.0,25758.0,每天都是车车车车,资深汽车达人 汽车博主 汽车视频自媒体,"IT数码,健康,旅游","迪拜-24每天都是车车车车IT数码,健康,旅游资深汽车达人 汽车博主 汽车视频自媒体"
9194,2232423695_5828016458,2232423695,5828016458,5828016458,董买买,1,m,上海,NaN,6,NaN,NaN,1990-01-01,173950.0,777.0,4117.0,电动吹、数码、旅游、评测。,汽车博主 微博原创视频博主,"新能源汽车,特斯拉,电动车","董买买电动吹、数码、旅游、评测。新能源汽车,特斯拉,电动车汽车博主 微博原创视频博主"

In [51]:
s_t = time.time()
col = df_m2['fan_id']
print(val_num(col))
print(time.time()-s_t)

100%|███████████████████████████████████████████████████████████████████████████| 9195/9195 [00:00<00:00, 18081.21it/s]

([6387925087, 3189768370, 6124733014, 5460987882, 5138022423, 6805258323, 2773483781, 5927600385, 5629806017, 5658117986, 7363102875, 5480909318, 5969546948, 6807359339, 5451550868, 7384076683, 5637148943, 5603594659, 6928994774, 5638198131, 6351230076, 6326059017, 7225737229, 3909095811, 6873415699, 2708471847, 6362760596, 5284828200, 6046089267, 2214593007, 7438598778, 6077547270, 6599738279, 3547333734, 7226787069, 6629099969, 7314868714, 5713693173, 5536484932, 6315577078, 5777657733, 6264197020, 7273975949, 2606764293, 6066016517, 6198137146, 2483032267, 2258637334, 5992616452, 6677336822, 5969548025, 3404726320, 5283775163, 2687500891, 2690646624, 7433356067, 6214910802, 3189769312, 5797578181, 6312429331, 3097495497, 7640975353, 5237639112, 5271193630, 2925529160, 6590302487, 6636440769, 7632588202, 2631929573, 1923092867, 6574575950, 5851058886, 3843035609, 6366958321, 6477058900, 2319455050, 3517977361, 2912949103, 3992982524, 3186627844, 7635730588, 2683306062, 5212471711, 6888096428, 2499806255, 6039799688, 3322939110, 5197793644, 3128953532, 5383392119, 5613030382, 5186260130, 5362420848, 6513757343, 6472863943, 5824844113, 3169849857, 6584013349, 6622810885, 5579477772, 2247103173, 2908754875, 7304385634, 5887754455, 7411335497, 3991929413, 2979005094, 6879707995, 1840251830, 5128586383, 5970593492, 7645169599, 5661263589, 5151656065, 6564088108, 2491419087, 2182089402, 5452598241, 7331647086, 5622468666, 6024073983, 6311379010, 6354370706, 3843031220, 3608150120, 5748293791, 3625975950, 5232394439, 5031067758, 7318012187, 5953814760, 5609881782, 5096079693, 3311403461, 6363808170, 6609174902, 6248464920, 5969543775, 5611979338, 5724176988, 6442451658, 6343885545, 6144656141, 5407507161, 7156532047, 5674894050, 7463764799, 5270143835, 1989149391, 5666505594, 6267339662, 6619661213, 7371490073, 6398411672, 2605712380, 3074425670, 5861540841, 1774191811, 3349152972, 5674894611, 1241515251, 5415896373, 2298479943, 5465179441, 3516925327, 2042627520, 6477055322, 5982127416, 5579474493, 5243930053, 1734346281, 7323256282, 6311380563, 2560624342, 5050992294, 3964667456, 6526338826, 5714740890, 7281313574, 5471471505, 5275387803, 5025826695, 6420432869, 5938087938, 3720349827, 5873076491, 3508537641, 6522145084, 5646584097, 6413093252, 5185210739, 6122637739, 5457840507, 6369053134, 5947525526, 6380587566, 2204109374, 2033191457, 3639609973, 1767901963, 6898584291, 3588229930, 5270145981, 5874125789, 2708474711, 5911874525, 2337279007, 5974789180, 6456085663, 5961157732, 5954866406, 6450842867, 2554334461, 5018488122, 5861543314, 7512002058, 6277828211, 7341084168, 6448746160, 1670385374, 6479154966, 3120566062, 6887051076, 2585792442, 5674897392, 3923775503, 5997858891, 6193942531, 2119176290, 1950355587, 6413095099, 6570381707, 5842670010, 3382710724, 2825916935, 5915021784, 5244981846, 6019879576, 5575283343, 5645538022, 7499420500, 5020586705, 6144660377, 6534730702, 5845816433, 3047167045, 5077210273, 5872030934, 5440017608, 3167748210, 2353004795, 3289382982, 6189744445, 6246367661, 5307892121, 6222250501, 7314866859, 6539969232, 5754585870, 2629829335, 7628391373, 5728371643, 1586496603, 5589959875, 5632951476, 6053430506, 1809843700, 3887072746, 1795163750, 6131025568, 3082815103, 5976884928, 5247076073, 5369759455, 6632245084, 2500855794, 7389317155, 5075109941, 2054162565, 5392828865, 7368345989, 5499783647, 5179968300, 6575623130, 7328500751, 3030387813, 5528095839, 7093619939, 6590303572, 6592400769, 2140147024, 3122662885, 5336206779, 6790581955, 5227155200, 2651852633, 6394220713, 5164241149, 6468669797, 6611276122, 7530877342, 5847912828, 5127541302, 2150634264, 5770318606, 2871005993, 5888807807, 5834282011, 2133857160, 2658145312, 7089427548, 3840938852, 3896513652, 7313822940, 5719987169, 2557476982, 6590300614, 5836374534, 6353322699, 7282361302, 6316622807, 2863662047, 7403996213, 1642071512, 3818915327, 5778703984, 5891950496, 1084229683, 6577719301, 5081401488, 6404704385, 5033167093, 7629441462, 2095057550, 5774510754, 6052383483, 3275754207, 2670726003, 5831133959, 6163532738, 5490347014, 6347033762, 5170531633, 7600082263, 5713694208, 2717912547, 6385831395, 1658850967, 5520756459, 5756686270, 5403316210, 5860495523, 5539631152, 6969888979, 6231691497, 6431969510, 6463426793, 6457135539, 2394952295, 6056579722, 5660218032, 7472157518, 2969572061, 5721035541, 5658121111, 7297040450, 7157579841, 7423918281, 2350907602, 3862954252, 3187671341, 7556039125, 6826230327, 5714739763, 7442793105, 1980760857, 5657068436, 6704596255, 1854932363, 7333742078, 2132805171, 7624197752, 6904874707, 7585400606, 5879367454, 1175455614, 7422871383, 6430918573, 2088765381, 5575280697, 1914701893, 6361712992, 6920604029, 1201670525, 6599739871, 6589254139, 5529143948, 2472544962, 7408192118, 6800018145, 1298140265, 2907704435, 1805651092, 7550799014, 5648682214, 5933895293, 5627711160, 7578062546, 6085938828, 6035607368, 6334451537, 2949648261, 6120542146, 2391805985, 6274683008, 6483349627, 7505711271, 7408194016, 7458525915, 7565480550, 1846546933, 6852448995, 5894050662, 5470425986, 5664412627, 6578770990, 6642734098, 5667558635, 6366953899, 2435842357, 1842349087, 2030044305, 5632952537, 5517610589, 5867835091, 7365726235, 5971644741, 2614104831, 7626298350, 3251634692, 5579473603, 6934234084, 6174017297, 1422919762, 6107957607, 5271194676, 7569673593, 7543460627, 2232423695, 7014973647, 7076839982, 7326401389, 7640974242, 5507122551, 7530874790, 3232762284, 5675944964, 6506417258, 7210012534, 7645172196, 7563383889, 7279215089, 1808794634, 5826937883, 5598348323, 7099909347, 7195329816, 2290091540, 5842667149, 5883561859, 7460620256, 5233445025, 5613029546, 5496637586, 5042604297, 7550798157, 7497321292, 1213205403, 6786386931, 3912240266, 7212108927, 5019536772, 7498370548, 6442454734, 6791630823, 7400853632, 7458525615, 1192235524, 7634686851, 7150245104, 6224347379, 2889875755, 5345640774, 7384072804, 5413798855, 2897216585, 5606738196, 5170531018, 2194673857, 2674922390, 6282019086, 7122978875, 2316307877, 6376390686, 7591691103, 2872051450, 6876563469, 3085961801, 2500857735, 6081742342, 2291140935, 7418678764, 7432310536, 3862958192, 7129268707, 7455377634, 7455378244, 6372200491, 2289045685, 5217719473, 7604273163, 7604274094, 7604274858, 7604275136, 7604275381, 7604276333, 7604273561, 7604274507, 7604274594, 7604274880, 7604275120, 7604277277, 1951403167, 3309309371, 7563378802, 7642022104, 5756682481, 2474639661, 7642022260, 7642022289, 7540310472, 6530531801, 7642022331, 7509901872, 7270826540, 7020217029, 6524240742, 7323255687, 7642022778, 6479152153, 5589959730, 7400850596, 5243929701, 7615808827, 7642023376, 7597983442, 6271534859, 6458181428, 7510951797, 7313819539, 7457474396, 7563381071, 7642024427, 7458523672, 7564429857, 7545555613, 7642024672, 7642024899, 7642024895, 7403998164, 7590645119, 6333402571, 3896512202, 6878662481, 7276072701, 6161436588, 6261051364, 7500468199, 7569674236, 7523537096, 7438602422, 7486837049, 7335842171, 5646586481, 6627005196, 6210720559, 7406097279, 6424630337, 7642027114, 7391417534, 7406097608, 6208618670, 6600786489, 6232736401, 2694841300, 6354371646, 6322914534, 7405045086, 6111102557, 3972007841, 7220496290, 7368345778, 7075793083, 7169116486, 6017780096, 7590644139, 7574915375, 7616858557, 6234835960, 6547311648, 3061844741, 7357860946, 5675945051, 7532973367, 7003442657, 6334451147, 2291142255, 6361714093, 7558139690, 6241128371, 2687504397, 5389684751, 1967132721, 3784314995, 7551848606, 7471108141, 7520391386, 6476009557, 6266294637, 6486495624, 6383735194, 6480204176, 6319772102, 5435818162, 5023728191, 7401899306, 6547310608, 6461327551, 2351958277, 6924798334, 5851056653, 2205159330, 2713718575, 6644830429, 5663364326, 7025464442, 6663700515, 3109031182, 7604273248, 7604274179, 7604275359, 7604275681, 7604276166, 3199206421, 3487566195, 5250222950, 6491736954, 2814380883, 5285876082, 6499079340, 7548698761, 6536827265, 7531925151, 1740640480, 7291800090, 2257589502, 7629439370, 2462058965, 6265246749, 1847596171, 3210740461, 5650777794, 7629441123, 5469375785, 7218400684, 2300579663, 6125785959, 2839544222, 5538580281, 5949622094, 5249173489, 7630491031, 7550800439, 5839524538, 6104814829, 7203717520, 5170529428, 5885658423, 5473568092, 5554308702, 7603226927, 2410678723, 5947526615, 5729423135, 5422186502, 6196037626, 5618272410, 7494175286, 3991932651, 5939134550, 5362417762, 5980030242, 5940184342, 1577060963, 6402608422, 1998589292, 7543459258, 5683285537, 5888806535, 5229252944, 5496635584, 7542407573, 1838153970, 5446304360, 2138047350, 3211789357, 6076498988, 1678771360, 1994394155, 5840571192, 5768220995, 5832180305, 3197113400, 7029655694, 1840253470, 5682236430, 6138368196, 2677019740, 6465523220, 2672820597, 6029313326, 6517949986, 5958012237, 6447694094, 6085935235, 2980054561, 6644830502, 6524244361, 7022313660, 6994002194, 5658116530, 5692719806, 6300893880, 6218056544, 6587155325, 2619343925, 5856298170, 7636780417, 6325012030, 6069159580, 5986322238, 7479494846, 5471471882, 1025509673, 6335498637, 2848983611, 7029656135, 5251271226, 5842668219, 5574232906, 5531241664, 3920628978, 5603593370, 7573867910, 3949989622, 6433017578, 5208281002, 5896146920, 5645537365, 7626297502, 5815406834, 5627711787, 6006247838, 5498737223, 5690626856, 5520757602, 7584355160, 5825893273, 7153385941, 6436160166, 2413823045, 7441744973, 6570378470, 7637828956, 7631537614, 7631537646, 6855591309, 3533702952, 7566527148, 7628393207, 5961157343, 6264195870, 2006977311, 2407533263, 5593107511, 7636782100, 5601496383, 1901072083, 6441406558, 5225058344, 6083842239, 6791631129, 7355765284, 7530878006, 7388271689, 7604273273, 7604273451, 7604274704, 7604275957, 7604277384, 7604274348, 7604274347, 7604274745, 7604274908, 7604276663, 7604277213, 7604277205, 7604273780, 7603228315, 5948572200, 7310676228, 6371152240, 5692719548, 2163213213, 6392120405, 5744100612, 5988419288, 6174017485, 2716862693, 6046091798, 2134903467, 6759124052, 1761610864, 5817503163, 2116030091, 5642391131, 2160070602, 6277828593, 5591011722, 5035267150, 5440017641, 7589595347, 2671774151, 2977958254, 3169848180, 5268049238, 5172629522, 5991567497, 5804921027, 1793065157, 6270484632, 5523898448, 1837105693, 1824523205, 5349835872, 1913652445, 6802113819, 6911165879, 5206181359, 7356811268, 2291140720, 6111103253, 5035264454, 7458523696, 5299505779, 6664751958, 1833962342, 6485445863, 7139757500, 5656022758, 5893001004, 5954867064, 5247078421, 5832183718, 6030365239, 5812262006, 7505712217, 7604273655, 5993663875, 7632586675, 7636781080, 5307893866, 5865738161, 7633637419, 7646220516, 2969569491, 1863323773, 2965377983, 2873098245, 6157238908, 7628395800, 7523533021, 5394924309, 6070207544, 6897534435, 6242174514, 5940185433, 7216302594, 5399120418, 7384074987, 2204109905, 7467962514, 5717889963, 7604273695, 7604274457, 7604275089, 7604275502, 7604277820, 7604277885, 7604274585, 6362759684, 2441087245, 5674896959, 6571429968, 3039826302, 1864368784, 2421164870, 3952084839, 7104103727, 2052064991, 5650780703, 5107614763, 7111444792, 7636782265, 6002053152, 6671041379, 6730810488, 3926917726, 6618615434, 6120539762, 7604276215, 7604276244, 7604278013, 7604277903, 7604274748, 7604275813, 7604278386, 5714742855, 6228545185, 6326061700, 1823473980, 5152703125, 7540312315, 5272242868, 7488934587, 7604273797, 7604274762, 7604274884, 7604274963, 7604275115, 7604275633, 7604277244, 7604278159, 6426722667, 5645534996, 6115299461, 2149585017, 1832915762, 7157580006, 7337939331, 2614104683, 3713012290, 7408193448, 5887754401, 6880760885, 1762657302, 7486834152, 7364151936, 5468324221, 7264536028, 2175796887, 2753562633, 3039824127, 6236932529, 7628393063, 7374637783, 6240079642, 6345985728, 1747980831, 6176117621, 3285189135, 3104834245, 1797261550, 5837425401, 3308260391, 3120565664, 5015342949, 5747250002, 1114641421, 5646581984, 7604275372, 7604275604, 7603229768, 7373587802, 6369054924, 7313817728, 2879390664, 7628391638, 7635732006, 7632587434, 1761611080, 3119514785, 7569672144, 7604275904, 5198843556, 5206183899, 7320113051, 5652873820, 2752513311, 5372904897, 1815087072, 5049944305, 6304041513, 5210377184, 6935286079, 5645537695, 2583696274, 7463768762, 6446649765, 2293236211, 6018826583, 1880102027, 1846546614, 5284827646, 6988763859, 7076839703, 3862954213, 2265973147, 5391778241, 6456083034, 5898240773, 6871319321, 6601835577, 5529142272, 1915749445, 5334107245, 5894047089, 5538579847, 5738858357, 1799358551, 7499417860, 3958377014, 7316966133, 5733616430, 5247077675, 5252321071, 5082451866, 5910827046, 7373590932, 5683286636, 5664412340, 6169825683, 7416583176, 5623518229, 5980034161, 6700405855, 3746562813, 6345983774, 6639585317, 5675944464, 3749712764, 2170557313, 1955594463, 5865737342, 6884955227, 5827986408, 2661287101, 6142560165, 5647632364, 5857349467, 2451575485, 5653926743, 2087716404, 3860858986, 6263144683, 7294945018, 6028263512, 5658117260, 5797577836, 5847909489, 6125782321, 7632586775, 6353324207, 2008025411, 1873808150, 5344594714, 6441405473, 6287264780, 6437211342, 5205135024, 7631540088, 6504321268, 1751126254, 6555701903, 5249176076, 7642024683, 7636779719, 7635731185, 7625245573, 7032800224, 7329550289, 7645172100, 6154097153, 5980030384, 3562014130, 7361005530, 5746199970, 5596253758, 5732569641, 6939480918, 5854205015, 2183140585, 2130707327, 5795481207, 6459229757, 7635732648, 7331646186, 1934627235, 5995760926, 5932846437, 7629443875, 6298797876, 5015340350, 6206523054, 1883242757, 6568282208, 7338985685, 1871709072, 5653923651, 6855594849, 3625977734, 5980031628, 6436159852, 2835350024, 2756710911, 5336208117, 5013245204, 5201989332, 5632955414, 6097469742, 5398069540, 5375001458, 2630878293, 6357517698, 6637487520, 6224352453, 7628390711, 3536848311, 7622101773, 5797580855, 7628395670, 7485784241, 5729420103, 5197793214, 6618615204, 6427774450, 5937041235, 5701111678, 2415924044, 7212105986, 7212106069, 7212106219, 7212106402, 7212106413, 7212107077, 7212107185, 7212107356, 7212107555, 7212107610, 7212107748, 7212107796, 7212107922, 7212108498, 7212108607, 7212108754, 7212108863, 7212109185, 7212109269, 7212109875, 7212110112, 7212110196, 7212110356, 7212110348, 7212110964, 7212111067, 7212106329, 7212107697, 7212107870, 7212110584, 7212110665, 7212110799, 7212110806, 7212108230, 7212108346, 7212108399, 7212108988, 7212109240, 7212109788, 7212110566, 3015705561, 6570378837, 5585765537, 6825181252, 5707399667, 5625610669, 6426727660, 7325356464, 5951717676, 5638197818, 2763003071, 3833597455, 6092227916, 5548019883, 7628390723, 7628394202, 7628390817, 7626293803, 7245660832, 7628391429, 7628391953, 7628392016, 7622100917, 7628392435, 7602178101, 7628393571, 7628393612, 7628394600, 7628395471, 7628395477, 5163188471, 3919581437, 7581204764, 3339719780, 6816797849, 7318015330, 1831862814, 7400850194, 7281313841, 6093278516, 5971643562, 6992957013, 2936016687, 6914315484, 1681917187, 7212106294, 7212106488, 7212106591, 7212106633, 7212106650, 7212106810, 7212106851, 7212106850, 7212108671, 1688212390, 6318723373, 2919238964, 6597645067, 7310672566, 6331303607, 6267341785, 5263854136, 2582643692, 6085936374, 6558844878, 3506440315, 5680139067, 5676993891, 6742348497, 6486495854, 5932843301, 6808404609, 2112881787, 3549432361, 5251272186, 3174043831, 6631196524, 5238686271, 2688550810, 6349128075, 6786387461, 5971642294, 3520069934, 6074402623, 5822745162, 6236934142, 6473913308, 7330596604, 7363102906, 1858079142, 1767901820, 2280653301, 6202331280, 2124417800, 5358223848, 6091179521, 6200233992, 7406096360, 7559185530, 2102396423, 3996125865, 7611616568, 6911168166, 7552896770, 7393513448, 5848961936, 5648683885, 5863641295, 5352983131, 2614102482, 5228203714, 2642413341, 6316623041, 7628394985, 7628395031, 7627346460, 3544190264, 5628756545, 1969226473, 5972689643, 5428479062, 5832182518, 6398413748, 5541727999, 7443845384, 5458891328, 1870660163, 6322918520, 7504658765, 1674578333, 6886000071, 2429552204, 2139097852, 6430921495, 6464472922, 6246369366, 7564430201, 6737105571, 6575625356, 1750078667, 7630490117, 1022362744, 3631221883, 7601132766, 6671043283, 5455741380, 7346323836, 7030706778, 3996127977, 6798972006, 5992612340, 6620710629, 7408194082, 7645169378, 6387929853, 3748659643, 7637828072, 7212109763, 7212109872, 1916800575, 7611614711, 3035629497, 7305431836, 7203719967, 7204770366, 7212110867, 5541725553, 5370809821, 5636097473, 7549750088, 7514096990, 5151655789, 5381294573, 7640978342, 7571768111, 1788871143, 7330595567, 1937772284, 7495223897, 7444893312, 1788870981, 5271192471, 5657070185, 5493492918, 1785728405, 7499419432, 1764754532, 1583353113, 7508856870, 6519002252, 7085230459, 3386904404, 2718958351, 6385828617, 7639927361, 7189040030, 6486496508, 5754586756, 6509561734, 3602910071, 5523900395, 2010122961, 6033510197, 5129637949, 6321869710, 6474962178, 7622099469, 6452937500, 1756366277, 6029313607, 7597986464, 6502223963, 1792017397, 6174016598, 6079645266, 6029314157, 5738858738, 6356470682, 7624200413, 5216670127, 5632950445, 7345277767, 1605372527, 7488931274, 5846862798, 7438603436, 6166675979, 7623148109, 6512706641, 6412047263, 5416945667, 7632587735, 5347741001, 3802140496, 6471811622, 7328500645, 3195014850, 7409238941, 2658142133, 7017073888, 2683309400, 7634682637, 7628395311, 7609520282, 3502246103, 3168798325, 6198137853, 6055526895, 5711596394, 6272583185, 1734349565, 5304746434, 2317358265, 5628756560, 2235564685, 2236617681, 7279215207, 5601493566, 7636779694, 7628391962, 7628392045, 7416580672, 7624200976, 5239738044, 5656021626, 6900683075, 2920285180, 7638879494, 5784995661, 3711964280, 5938087995, 2713717563, 7174361896, 6117393738, 1660945571, 2864710142, 7347373786, 5658117743, 6807357351, 2531266027, 7565479590, 6125783643, 5721031690, 2347766322, 5848957433, 6262099114, 5136977651, 7305432984, 5866788048, 5669654784, 7483689881, 1785727537, 5170533386, 6119490981, 7628391214, 6896487225, 6240077430, 7400851462, 3319795330, 7628391203, 6032461856, 5728371502, 5810160406, 5769269460, 7364152451, 1869615411, 7628395249, 5403312951, 3124757303, 6935286022, 7358911176, 5201988585, 3836744110, 5469373217, 6656362641, 3300918457, 7628391307, 5652874874, 5193599721, 6900681748, 5818551688, 6414143105, 5949625111, 7632587608, 6309284479, 5706351492, 3608152194, 7496271020, 3955232028, 7628393973, 3162510074, 6387929143, 6489637683, 6616516979, 7457475067, 7632587049, 5663360519, 6762271582, 5671752404, 7559186572, 3041919821, 3183480684, 5531239280, 7596935684, 6067061803, 6604981263, 6587158738, 7607422096, 2850033671, 2297432151, 3506443320, 5150607548, 6203376677, 5250220959, 7384073675, 6400510021, 5045748838, 7471106591, 7628395733, 6069160207, 3641706667, 7628391639, 7628393169, 7628394319, 6509563308, 6556749820, 5584717020, 7043286271, 6298798159, 7233082012, 2958034731, 3830451205, 3218081713, 2545943802, 5969546367, 7582254323, 7172262742, 6513757293, 5047849079, 3994028037, 1707083081, 7414482313, 6925845918, 5925504362, 6637491333, 7628391867, 7628391861, 7482639836, 1815086872, 3164606267, 6599742133, 5286922720, 5888804628, 6448746384, 6372201019, 1571819105, 7534020075, 6654264819, 6226445841, 6309283331, 6508513204, 7312770512, 5071964119, 6037705673, 2014316040, 5285873699, 3779069470, 7380930640, 6692014108, 5688526469, 5565846769, 7636782099, 6903826121, 7644120857, 1870661961, 7366249165, 5758783419, 6056578273, 7272924982, 7628392259, 7628392647, 1940915945, 7003440976, 5833231334, 1664092063, 1951401805, 7628395566, 7521440021, 6442452990, 7386171414, 7588546729, 6890196697, 6222252165, 2509246241, 5659166871, 7403998770, 6608128788, 3209696452, 6585059808, 7402949711, 6642732484, 6246369997, 3319796963, 6894389775, 7500467393, 7628393044, 7642024849, 5400171718, 5210378563, 7628393151, 7344228971, 5972692668, 3568306760, 2657096975, 5132782433, 7610567583, 5269097477, 6434067197, 7607421992, 7636782210, 7579110541, 3659533371, 1784681352, 7626296615, 5887757608, 5970594967, 7159680283, 601253

In [52]:
list_user,list_num = val_num(col)
df_travel_num = pd.DataFrame(data=list_user,columns=['user_id'])
df_travel_num['focus_travel_num'] = pd.Series(list_num)
df_travel_num

100%|███████████████████████████████████████████████████████████████████████████| 9195/9195 [00:00<00:00, 17343.09it/s]

         user_id  focus_travel_num
0     6387925087                 1
1     3189768370                 1
2     6124733014                 1
3     5460987882                 1
4     5138022423                 1
...          ...               ...
1695  6468670381                12
1696  2157974514               166
1697  3172996364                 9
1698  3195016464                 1
1699  7604278546                 4

[1700 rows x 2 columns]

In [53]:
df_merge2

         user_id  focus_kol_num  focus_makeup_num  focus_food_num
0     7646220516             33               8.0             9.0
1     7645172196            135               2.0            46.0
2     7645172100             76              11.0             7.0
3     7645172015             41               NaN             NaN
4     7645169808             16               NaN             8.0
...          ...            ...               ...             ...
1989  1084229683             51               1.0             1.0
1990  1025509673             75               NaN             2.0
1991  1022362744             50               NaN             5.0
1992  1011876243             24               3.0             4.0
1993  1008733090             28               NaN             NaN

[1994 rows x 4 columns]

In [55]:
df_merge3 = pd.merge(df_merge2,df_travel_num,on='user_id',
                    how='left',sort=False)
df_merge3

,user_id,focus_kol_num,focus_makeup_num,focus_food_num,focus_travel_num
0,7646220516,33,8.0,9.0,19.0
1,7645172196,135,2.0,46.0,6.0
2,7645172100,76,11.0,7.0,2.0
3,7645172015,41,NaN,NaN,1.0
4,7645169808,16,NaN,8.0,NaN
...,...,...,...,...,...
1989,1084229683,51,1.0,1.0,1.0
1990,1025509673,75,NaN,2.0,1.0
1991,1022362744,50,NaN,5.0,8.0
1992,1011876243,24,3.0,4.0,NaN
1993,1008733090,28,NaN,NaN,NaN

## 游戏博主数目

- 导入文件 游戏博主

In [56]:
df_game_kol = pd.read_csv('D:/datasets/qianyi/user_label/method/based_on_user_focusing_kol/file/game_kol_gt10w.csv',encoding='utf-8')
df_game_kol

,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con
0,1271018062,星语美食娱乐,2,f,海外,美国,0,·信达外国语学校,NaN,NaN,104193.0,91.0,5125.0,Q:326888528,NaN,"星座命理,游戏,美剧","星语美食娱乐Q:326888528星座命理,游戏,美剧nan"
1,2097210323,正宗好游戏,2,f,四川,成都,0,NaN,NaN,01-01,1031574.0,498.0,7091.0,最新最全的游戏综合资讯~尽在@正宗好游戏,NaN,"极品飞车,实况2014,游戏爱好者","正宗好游戏最新最全的游戏综合资讯~尽在@正宗好游戏极品飞车,实况2014,游戏爱好者nan"
2,1233143520,微为烟夕罗,1,f,上海,闸北区,7,NaN,NaN,NaN,152037.0,747.0,70060.0,叫我萝卜就口以 淘宝店铺：烟夕罗捏脸铺子,游戏博主,"微博刷屏王,宅,要命的处女座","微为烟夕罗叫我萝卜就口以 淘宝店铺：烟夕罗捏脸铺子微博刷屏王,宅,要命的处女座游戏博主"
3,5360483141,Ow_Diya,1,m,上海,NaN,7,NaN,·上海龙之队,1999-07-30,135387.0,345.0,868.0,就是人帅了一点游戏也打得好没办法的。,Shanghai Dragons上海龙之队成员,"游戏,vgdiya,电子竞技","Ow_Diya就是人帅了一点游戏也打得好没办法的。游戏,vgdiya,电子竞技Shangha..."
4,3938580330,极客羊,1,m,广东,广州,6,NaN,·极客羊工作室（Geek Sheep Studio）2018年-至今,2018-04-13,106198.0,11.0,253.0,“万物皆可盘彩蛋，世事均能抠细节” 坚持用心做好每一个彩蛋视频～ 每周二周五更新～ (≧▽≦...,游戏博主,"彩蛋,游戏,软件",极客羊“万物皆可盘彩蛋，世事均能抠细节” 坚持用心做好每一个彩蛋视频～ 每周二周五更新～ (...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4582,5035554105,PopStar消灭星星,1,f,北京,海淀区,0,NaN,NaN,1979-07-01,586657.0,360.0,2096.0,《PopStar!消灭星星官方正版》是最经典的消除类休闲手游，全球拥有超过4亿用户，始终是休...,PopStar消灭星星官方微博,"爱猫,八卦,好玩的",PopStar消灭星星《PopStar!消灭星星官方正版》是最经典的消除类休闲手游，全球拥有...
4583,5556747367,手游主播君,1,f,海外,NaN,0,NaN,NaN,NaN,1138509.0,150.0,50.0,知名游戏博主,游戏博主,"名人明星,新闻资讯,游戏动漫","手游主播君知名游戏博主名人明星,新闻资讯,游戏动漫游戏博主"
4584,3985622865,剑魂之刃官博,1,f,北京,海淀区,0,NaN,·北京昆仑乐享网络技术有限公司,0001-00-00,1141378.0,55.0,108.0,全球首款手势操控的格斗手游《剑魂之刃》，备受国民瞩目的IOS版8.13日正式火爆上线！超值大...,剑魂之刃官方微博,"手势格斗,竞技,拳皇",剑魂之刃官博全球首款手势操控的格斗手游《剑魂之刃》，备受国民瞩目的IOS版8.13日正式火爆...
4585,3338517620,NBA梦之队官博,1,m,NaN,NaN,0,NaN,NaN,NaN,1066395.0,102.0,8372.0,NBA官方授权的正版篮球社交手游 《NBA梦之队》，官网nba.mobage.cn/home,NBA梦之队官方微博,NaN,NBA梦之队官博NBA官方授权的正版篮球社交手游 《NBA梦之队》，官网nba.mobage...
4586,6570002919,麦游手游,1,m,NaN,NaN,5,NaN,NaN,NaN,122651.0,1280.0,431.0,"欢迎喜欢玩游戏的朋友加我好友互相关注 就爱玩BT手游盒子,玩家优选平台,千款热门精品手游任选...",游戏博主,NaN,"麦游手游欢迎喜欢玩游戏的朋友加我好友互相关注 就爱玩BT手游盒子,玩家优选平台,千款热门精品..."

In [57]:
df_m2 = pd.merge(df_ff,df_game_kol,left_on='followed_id',right_on='kol_id',how='inner')
df_m2

,_id,fan_id,followed_id,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con
0,5138022423_1762257041,5138022423,1762257041,1762257041,扶他柠檬茶,1,f,其他,NaN,7,NaN,NaN,NaN,2202941.0,361.0,17157.0,微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com,知名读物博主 超话主持人（扶他柠檬茶超话）,"腐,游戏,脑洞","扶他柠檬茶微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com腐,游戏..."
1,5939134550_1762257041,5939134550,1762257041,1762257041,扶他柠檬茶,1,f,其他,NaN,7,NaN,NaN,NaN,2202941.0,361.0,17157.0,微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com,知名读物博主 超话主持人（扶他柠檬茶超话）,"腐,游戏,脑洞","扶他柠檬茶微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com腐,游戏..."
2,1969226473_1762257041,1969226473,1762257041,1762257041,扶他柠檬茶,1,f,其他,NaN,7,NaN,NaN,NaN,2202941.0,361.0,17157.0,微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com,知名读物博主 超话主持人（扶他柠檬茶超话）,"腐,游戏,脑洞","扶他柠檬茶微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com腐,游戏..."
3,7043286271_1762257041,7043286271,1762257041,1762257041,扶他柠檬茶,1,f,其他,NaN,7,NaN,NaN,NaN,2202941.0,361.0,17157.0,微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com,知名读物博主 超话主持人（扶他柠檬茶超话）,"腐,游戏,脑洞","扶他柠檬茶微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com腐,游戏..."
4,5407509003_1762257041,5407509003,1762257041,1762257041,扶他柠檬茶,1,f,其他,NaN,7,NaN,NaN,NaN,2202941.0,361.0,17157.0,微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com,知名读物博主 超话主持人（扶他柠檬茶超话）,"腐,游戏,脑洞","扶他柠檬茶微博不著名博主、战略忽悠局师爷-工作联系：862998740@qq.com腐,游戏..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2388,3209696452_1448655683,3209696452,1448655683,1448655683,Maggie_小麦,2,f,北京,NaN,6,NaN,NaN,0001-00-00,249243.0,462.0,4432.0,我想要个Jarvis！！！爱养植物的超蝙党，那个叫拉顿哈给顿的康纳是我男神,NaN,"墨明棋妙,游戏渣,配音",Maggie_小麦我想要个Jarvis！！！爱养植物的超蝙党，那个叫拉顿哈给顿的康纳是我男神...
2389,2183140585_6224745881,2183140585,6224745881,6224745881,段段以及南墙,1,m,四川,NaN,6,NaN,·平安京·平安京·,1995-06-29,231545.0,264.0,14856.0,谁人如此激进，仍不及我为你那样勇,知名游戏博主 游戏视频自媒体 微博原创视频博主,"斗技,阴阳师","段段以及南墙谁人如此激进，仍不及我为你那样勇斗技,阴阳师知名游戏博主 游戏视频自媒体 微博原..."
2390,6315578618_6154230089,6315578618,6154230089,6154230089,网易新游资讯,2,m,天津,西青区,6,·北京交通大学12级,·网易科技有限公司,1988-11-12,350068.0,78.0,1834.0,游戏热爱者,NaN,"游戏,明星","网易新游资讯游戏热爱者游戏,明星nan"
2391,3209696452_6364348124,3209696452,6364348124,6364348124,食物语手游,1,f,广东,广州,6,·中山大学18级,NaN,2017-09-14,455642.0,66.0,1493.0,《食物语》是一款女性向中华美食拟人手游，那些平日里你所熟知或者陌生的中华美食将化为形象各异的...,手游《食物语》官方微博,"吃货,动漫,游戏动漫",食物语手游《食物语》是一款女性向中华美食拟人手游，那些平日里你所熟知或者陌生的中华美食将化为...
2392,3209696452_6364348124,3209696452,6364348124,6364348124,食物语手游,1,f,广东,广州,6,·中山大学18级,NaN,2017-09-14,455642.0,66.0,1493.0,《食物语》是一款女性向中华美食拟人手游，那些平日里你所熟知或者陌生的中华美食将化为形象各异的...,手游《食物语》官方微博,"吃货,动漫,游戏动漫",食物语手游《食物语》是一款女性向中华美食拟人手游，那些平日里你所熟知或者陌生的中华美食将化为...

In [58]:
col = df_m2['fan_id']
list_user,list_num = val_num(col)
df_game_num = pd.DataFrame(data=list_user,columns=['user_id'])
df_game_num['focus_game_num'] = pd.Series(list_num)
df_game_num

100%|███████████████████████████████████████████████████████████████████████████| 2393/2393 [00:00<00:00, 22912.11it/s]

        user_id  focus_game_num
0    5138022423               1
1    5939134550               1
2    1969226473               1
3    7043286271               1
4    5407509003               1
..          ...             ...
921  6642734098               4
922  6319772102               7
923  3896513652               1
924  5284828200               9
925  5812262006              10

[926 rows x 2 columns]

In [60]:
df_merge4 = pd.merge(df_merge3,df_game_num,on='user_id',
                    how='left',sort=False)
df_merge4

,user_id,focus_kol_num,focus_makeup_num,focus_food_num,focus_travel_num,focus_game_num
0,7646220516,33,8.0,9.0,19.0,NaN
1,7645172196,135,2.0,46.0,6.0,17.0
2,7645172100,76,11.0,7.0,2.0,3.0
3,7645172015,41,NaN,NaN,1.0,NaN
4,7645169808,16,NaN,8.0,NaN,NaN
...,...,...,...,...,...,...
1989,1084229683,51,1.0,1.0,1.0,NaN
1990,1025509673,75,NaN,2.0,1.0,NaN
1991,1022362744,50,NaN,5.0,8.0,3.0
1992,1011876243,24,3.0,4.0,NaN,NaN
1993,1008733090,28,NaN,NaN,NaN,NaN

- merge

- 载入文件 搞笑类博主

In [ ]:
# df_fun_kol = pd.read_csv('D:/datasets/qianyi/user_label/method/based_on_user_focusing_kol/file/fun_kol_gt10w.csv',
#                          encoding='utf-8')
# df_m2 = pd.merge(df_ff,df_fun_kol,left_on='followed_id',right_on='kol_id',how='inner')
# col = df_m2['fan_id']
# list_user,list_num = val_num(col)
# df_fun_num = pd.DataFrame(data=list_user,columns=['user_id'])
# df_fun_num['focus_fun_num'] = pd.Series(list_num)
# df_merge3 = pd.merge(df_merge2,df_food_num,on='user_id',
#                     how='left',sort=False)

In [63]:
df_fun_kol = pd.read_csv('D:/datasets/qianyi/user_label/method/based_on_user_focusing_kol/file/kol/fun_kol_gt10w.csv',
                    encoding='utf-8')
df_fun_kol

,kol_id,nick_name,user_type,gender,province,city,vip_level,education,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con,con_seq
0,2301726604,卓宣zoey,0,f,北京,NaN,7,NaN,NaN,天秤座,2870800.0,394.0,1510.0,没有人能定义我（合作加v：jacm188）,美妆博主,"生活,搞笑视频,搞笑图片","卓宣zoey没有人能定义我（合作加v：jacm188）生活,搞笑视频,搞笑图片美妆博主","['卓宣', '人能', '定义', '合作', '生活', '搞笑', '视频', '搞笑..."
1,3015928115,国人养生殿孝基,0,m,北京,西城区,1,NaN,NaN,NaN,104664.0,2195.0,1110.0,XXXWL9527❤V,搞笑幽默博主,美女,国人养生殿孝基XXXWL9527❤V美女搞笑幽默博主,"['国人', '养生', '美女', '搞笑', '幽默', '博主']"
2,5025857653,果子,0,m,河南,郑州,6,NaN,NaN,狮子座,20166337.0,234.0,99327.0,商务合作v：55188955,搞笑幽默博主 微博原创视频博主 微博VLOG博主,NaN,果子商务合作v：55188955nan搞笑幽默博主 微博原创视频博主 微博VLOG博主,"['果子', '商务', '合作', '搞笑', '幽默', '博主', '原创', '视频..."
3,5362566664,著名造型师peter,0,m,福建,NaN,7,NaN,·MAXhairsalon2015年-2016年·昕薇杂志,1980-03-11,170455.0,319.0,1618.0,NaN,时尚博主,搞笑幽默,著名造型师peternan搞笑幽默时尚博主,"['著名', '造型师', '搞笑', '幽默', '时尚', '博主']"
4,6811589462,喝大了,1,m,浙江,NaN,5,·浙江大学14级,·,1996-05-17,2026534.0,29.0,5774.0,关注我的听说都找到配对了。,搞笑幽默博主,NaN,喝大了关注我的听说都找到配对了。nan搞笑幽默博主,"['听说', '找到', '配对', '搞笑', '幽默', '博主']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14468,2419121401,就笑了怎么,1,m,NaN,NaN,6,NaN,NaN,NaN,275877.0,500.0,695.0,哈哈哈哈，不想再被硬邦邦的现实撞得人仰马翻,搞笑幽默博主,NaN,就笑了怎么哈哈哈哈，不想再被硬邦邦的现实撞得人仰马翻nan搞笑幽默博主,"['不想', '现实', '搞笑', '幽默', '博主']"
14469,1974750773,幽默咖1,2,m,NaN,NaN,2,NaN,NaN,NaN,122913.0,1921.0,225.0,🔥世界顶尖搞笑大咖cc,NaN,NaN,幽默咖1🔥世界顶尖搞笑大咖ccnannan,"['幽默', '顶尖', '搞笑']"
14470,1788096093,银河系小喷子,1,m,NaN,NaN,6,NaN,NaN,NaN,126427.0,994.0,1876.0,说那么多都是为了什么呢？,搞笑幽默博主,NaN,银河系小喷子说那么多都是为了什么呢？nan搞笑幽默博主,"['银河系', '喷子', '搞笑', '幽默', '博主']"
14471,3889228788,欢乐的Jony格轮,1,f,NaN,NaN,0,NaN,NaN,NaN,100911.0,2870.0,2129.0,只有经历过地狱般的折磨，才有征服天堂的力量。只有流过血的手指才能弹出世间的绝唱。,搞笑幽默博主,NaN,欢乐的Jony格轮只有经历过地狱般的折磨，才有征服天堂的力量。只有流过血的手指才能弹出世间的...,"['欢乐', '格轮', '地狱', '折磨', '征服', '天堂', '力量', '流过..."
14472,2071959200,幽默小智慧,2,m,NaN,NaN,4,NaN,NaN,NaN,141796.0,2099.0,29845.0,你想快乐吗？想心情愉悦吗？相信——幽默小智慧.会每天为你带来不一样的快乐和愉悦哦！（•精灵•...,NaN,NaN,幽默小智慧你想快乐吗？想心情愉悦吗？相信——幽默小智慧.会每天为你带来不一样的快乐和愉悦哦！...,"['幽默', '智慧', '快乐', '愉悦', '相信', '幽默', '智慧', '带来..."

In [64]:
df_m2 = pd.merge(df_ff,df_fun_kol,left_on='followed_id',right_on='kol_id',how='inner')
df_m2

,_id,fan_id,followed_id,kol_id,nick_name,user_type,gender,province,city,vip_level,...,work,birthday,fan_num,follow_num,tweet_num,brief_intro,authentication,label,kol_con,con_seq
0,6387925087_5331040243,6387925087,5331040243,5331040243,沈月,1,f,湖南,NaN,7,...,·工夫真言影业有限公司,1997-02-27,12239547.0,283.0,869.0,˙Ꙫ˙,工夫真言影业签约演员,搞笑幽默,沈月˙Ꙫ˙搞笑幽默工夫真言影业签约演员,"['沈月', '搞笑', '幽默', '工夫', '真言', '影业', '签约', '演员']"
1,6387925087_5331040243,6387925087,5331040243,5331040243,沈月,1,f,湖南,NaN,7,...,·工夫真言影业有限公司,1997-02-27,12239547.0,283.0,869.0,˙Ꙫ˙,工夫真言影业签约演员,搞笑幽默,沈月˙Ꙫ˙搞笑幽默工夫真言影业签约演员,"['沈月', '搞笑', '幽默', '工夫', '真言', '影业', '签约', '演员']"
2,3289382982_5331040243,3289382982,5331040243,5331040243,沈月,1,f,湖南,NaN,7,...,·工夫真言影业有限公司,1997-02-27,12239547.0,283.0,869.0,˙Ꙫ˙,工夫真言影业签约演员,搞笑幽默,沈月˙Ꙫ˙搞笑幽默工夫真言影业签约演员,"['沈月', '搞笑', '幽默', '工夫', '真言', '影业', '签约', '演员']"
3,3289382982_5331040243,3289382982,5331040243,5331040243,沈月,1,f,湖南,NaN,7,...,·工夫真言影业有限公司,1997-02-27,12239547.0,283.0,869.0,˙Ꙫ˙,工夫真言影业签约演员,搞笑幽默,沈月˙Ꙫ˙搞笑幽默工夫真言影业签约演员,"['沈月', '搞笑', '幽默', '工夫', '真言', '影业', '签约', '演员']"
4,6436159852_5331040243,6436159852,5331040243,5331040243,沈月,1,f,湖南,NaN,7,...,·工夫真言影业有限公司,1997-02-27,12239547.0,283.0,869.0,˙Ꙫ˙,工夫真言影业签约演员,搞笑幽默,沈月˙Ꙫ˙搞笑幽默工夫真言影业签约演员,"['沈月', '搞笑', '幽默', '工夫', '真言', '影业', '签约', '演员']"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15550,6474962178_6085757546,6474962178,6085757546,6085757546,嗨小米的日常,1,m,北京,东城区,5,...,NaN,0001-00-00,164087.0,182.0,34913.0,微博综合类搞笑幽默视频,搞笑幽默视频博主,NaN,嗨小米的日常微博综合类搞笑幽默视频nan搞笑幽默视频博主,"['小米', '综合类', '搞笑', '幽默', '视频', '搞笑', '幽默', '视..."
15551,3209696452_1878349083,3209696452,1878349083,1878349083,不咸__,2,f,广东,NaN,6,...,NaN,双鱼座,152016.0,382.0,4201.0,NaN,NaN,"搞笑幽默,瓶邪","不咸__nan搞笑幽默,瓶邪nan","['搞笑', '幽默']"
15552,3209696452_1878349083,3209696452,1878349083,1878349083,不咸__,2,f,广东,NaN,6,...,NaN,双鱼座,152016.0,382.0,4201.0,NaN,NaN,"搞笑幽默,瓶邪","不咸__nan搞笑幽默,瓶邪nan","['搞笑', '幽默']"
15553,3209696452_2057283547,3209696452,2057283547,2057283547,雾十,1,f,山西,太原,7,...,NaN,天蝎座,116315.0,419.0,6274.0,晋江专栏id：332176。任何涉及到版权的事，都请联系晋江。爱大家，么么哒~,网络作家 晋江签约作者,"搞笑幽默,动漫,腐女子","雾十晋江专栏id：332176。任何涉及到版权的事，都请联系晋江。爱大家，么么哒~搞笑幽默,...","['晋江', '专栏', '涉及', '版权', '联系', '晋江', '大家', '搞笑..."
15554,3209696452_2057283547,3209696452,2057283547,2057283547,雾十,1,f,山西,太原,7,...,NaN,天蝎座,116315.0,419.0,6274.0,晋江专栏id：332176。任何涉及到版权的事，都请联系晋江。爱大家，么么哒~,网络作家 晋江签约作者,"搞笑幽默,动漫,腐女子","雾十晋江专栏id：332176。任何涉及到版权的事，都请联系晋江。爱大家，么么哒~搞笑幽默,...","['晋江', '专栏', '涉及', '版权', '联系', '晋江', '大家', '搞笑..."

In [65]:
col = df_m2['fan_id']
list_user,list_num = val_num(col)
df_fun_num = pd.DataFrame(data=list_user,columns=['user_id'])
df_fun_num['focus_fun_num'] = pd.Series(list_num)
df_fun_num

100%|█████████████████████████████████████████████████████████████████████████| 15555/15555 [00:00<00:00, 80519.33it/s]

         user_id  focus_fun_num
0     6387925087              2
1     3289382982              2
2     6436159852              2
3     5692719548              2
4     5707399667              2
...          ...            ...
1673  6935286022            156
1674  6501175944             85
1675  5894050662            127
1676  6387930240             60
1677  1880102027              7

[1678 rows x 2 columns]

In [66]:
df_merge5 = pd.merge(df_merge4,df_fun_num,on='user_id',
                    how='left',sort=False)
df_merge5

,user_id,focus_kol_num,focus_makeup_num,focus_food_num,focus_travel_num,focus_game_num,focus_fun_num
0,7646220516,33,8.0,9.0,19.0,NaN,4.0
1,7645172196,135,2.0,46.0,6.0,17.0,2.0
2,7645172100,76,11.0,7.0,2.0,3.0,33.0
3,7645172015,41,NaN,NaN,1.0,NaN,8.0
4,7645169808,16,NaN,8.0,NaN,NaN,12.0
...,...,...,...,...,...,...,...
1989,1084229683,51,1.0,1.0,1.0,NaN,10.0
1990,1025509673,75,NaN,2.0,1.0,NaN,1.0
1991,1022362744,50,NaN,5.0,8.0,3.0,NaN
1992,1011876243,24,3.0,4.0,NaN,NaN,28.0
1993,1008733090,28,NaN,NaN,NaN,NaN,4.0

- 导入文件 user信息

In [68]:
df_user = pd.read_csv('D:/datasets/large_file/user6m.csv',encoding='utf-8')
df_user

D:\software\anaconda\envs\nlp\lib\site-packages\IPython\core\interactiveshell.py:3437: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24,25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,_id,authentication,bg_img_url,birthday,brief_intro,city,cn_crawled,crawl_at,crawl_at_timestamp,education,...,nick_name,person_url,province,sentiment,sex_orientation,tweet_num,user_type,v,vip_level,work
0,2917160407,NaN,https://wx4.sinaimg.cn/crop.0.0.640.640.640/ad...,1996-03-30,天将黑未黑时最浪漫 人不近不远最自然,保定,True,2021-08-02T19:44:21.787Z,1627904661,NaN,...,Lccccc_,https://weibo.com/u/2917160407,河北,NaN,NaN,176,0.0,NaN,3,NaN
1,5770326762,NaN,https://tva2.sinaimg.cn/crop.0.0.640.640.640/a...,1989-11-08,公开微信997865467,杭州,True,2021-08-02T19:34:04.907Z,1627904044,·杭州师范大学07级,...,最美校花任琳jones,https://weibo.com/u/5770326762,浙江,NaN,NaN,2411,0.0,NaN,1,·广告公司2013年-2014年
2,7521453134,NaN,https://tva1.sinaimg.cn/crop.0.0.640.640.640/5...,NaN,啥时候中次大奖让我快乐快乐,NaN,True,2021-08-02T21:16:07.104Z,1627910167,NaN,...,哈利啵菜_,https://weibo.com/u/7521453134,其他,NaN,NaN,2,0.0,NaN,0,NaN
3,2048956025,NaN,NaN,1998-04-01,我是我的精神领袖🌈,万州区,NaN,1626199473833,1626170673,NaN,...,今天也要努力学习变富婆,NaN,重庆,NaN,NaN,739,0.0,NaN,：6级,NaN
4,7603237614,NaN,https://tva1.sinaimg.cn/crop.0.0.640.640.640/5...,NaN,NaN,NaN,True,2021-08-02T20:27:47.324Z,1627907267,NaN,...,用户7603237614,https://weibo.com/u/7603237614,其他,NaN,NaN,0,0.0,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6105007,7206398338,NaN,https://tva1.sinaimg.cn/crop.0.0.640.640.640/5...,NaN,NaN,NaN,True,2021-08-02T11:57:11.539Z,1627876631,NaN,...,E峰峰峰购,NaN,其他,NaN,NaN,0,0.0,NaN,NaN,NaN
6105008,7216727352,NaN,https://tva1.sinaimg.cn/crop.0.0.640.640.640/5...,NaN,NaN,NaN,True,2021-08-02T13:17:11.588Z,1627881431,NaN,...,Wangyxin哦像,NaN,其他,NaN,NaN,0,0.0,NaN,NaN,NaN
6105009,7163510847,NaN,https://tva1.sinaimg.cn/crop.0.0.640.640.640/5...,NaN,NaN,NaN,True,2021-08-02T11:56:38.972Z,1627876598,NaN,...,yunzhongy役,NaN,其他,NaN,NaN,0,0.0,NaN,NaN,NaN
6105010,7116342151,NaN,https://tva1.sinaimg.cn/crop.0.0.640.640.640/5...,NaN,NaN,NaN,True,2021-08-02T13:08:12.442Z,1627880892,NaN,...,他妈呀旦,NaN,其他,NaN,NaN,0,0.0,NaN,NaN,NaN
6105011,7645291838,NaN,https://tva1.sinaimg.cn/crop.0.0.640.640.640/5...,NaN,NaN,NaN,True,2021-08-02T12:59:13.502Z,1627880353,NaN,...,月亮化掉了17952,NaN,其他,NaN,NaN,6,0.0,NaN,NaN,NaN

In [69]:
# df_user.columns

Index(['_id', 'authentication', 'bg_img_url', 'birthday', 'brief_intro',
       'city', 'cn_crawled', 'crawl_at', 'crawl_at_timestamp', 'education',
       'fan_num', 'follow_num', 'gender', 'head_img_url', 'label', 'm_crawled',
       'nick_name', 'person_url', 'province', 'sentiment', 'sex_orientation',
       'tweet_num', 'user_type', 'v', 'vip_level', 'work'],
      dtype='object')

In [70]:
df_user_briinfo = df_user[['_id','nick_name','follow_num','fan_num','tweet_num']]
df_user_briinfo

                _id     nick_name follow_num fan_num tweet_num
0        2917160407       Lccccc_        212    1098       176
1        5770326762   最美校花任琳jones       1410     221      2411
2        7521453134         哈利啵菜_         84       1         2
3        2048956025   今天也要努力学习变富婆        337     266       739
4        7603237614  用户7603237614        591       1         0
...             ...           ...        ...     ...       ...
6105007  7206398338         E峰峰峰购         36       1         0
6105008  7216727352    Wangyxin哦像         86       1         0
6105009  7163510847    yunzhongy役         15       1         0
6105010  7116342151          他妈呀旦         16       1         0
6105011  7645291838    月亮化掉了17952         44       1         6

[6105012 rows x 5 columns]

In [71]:
df_user_focus_kol = pd.merge(df_merge5,df_user_briinfo,left_on='user_id',right_on='_id')
df_user_focus_kol

,user_id,focus_kol_num,focus_makeup_num,focus_food_num,focus_travel_num,focus_game_num,focus_fun_num,_id,nick_name,follow_num,fan_num,tweet_num
0,7646220516,33,8.0,9.0,19.0,NaN,4.0,7646220516,用户7646220516,62,1,0
1,7645172196,135,2.0,46.0,6.0,17.0,2.0,7645172196,NaN,585,1246,651
2,7645172100,76,11.0,7.0,2.0,3.0,33.0,7645172100,用户7645172100,158,1,0
3,7645172015,41,NaN,NaN,1.0,NaN,8.0,7645172015,NaN,176,11,3
4,7645169808,16,NaN,8.0,NaN,NaN,12.0,7645169808,优选201012,25,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1988,1084229683,51,1.0,1.0,1.0,NaN,10.0,1084229683,卉卉的窝,94,91,14
1989,1025509673,75,NaN,2.0,1.0,NaN,1.0,1025509673,靓哩个靓妹,123,24,17
1990,1022362744,50,NaN,5.0,8.0,3.0,NaN,1022362744,若欧得,128,79,33
1991,1011876243,24,3.0,4.0,NaN,NaN,28.0,1011876243,水槽里的NPC河马,87,44,343
1992,1008733090,28,NaN,NaN,NaN,NaN,4.0,1008733090,反叛男孩,83,234,54

- 生成文件

In [72]:
df_user_focus_kol.to_csv('D:/datasets/qianyi/user_label/method/based_on_user_focusing_kol/file/user_kol_num/2kuser_kol.csv')

In [74]:
df_user_focus_kol.isna().sum()

user_id                0
focus_kol_num          0
focus_makeup_num     598
focus_food_num       340
focus_travel_num     293
focus_game_num      1067
focus_fun_num        315
_id                    0
nick_name             11
follow_num             0
fan_num                0
tweet_num              0
dtype: int64

### 缺失值解读 :

1.用户关注美妆、美食、旅行、游戏、搞笑类博主的数据缺失值：由目前爬取到的数据未能检索到用户关注此类型的博主

2.昵称缺失值：可能是账户异常，之前爬取的表格有相应数据，最近爬取的表格中则无相应数据